import Link from "next/link";
import { policyPageContext } from "@/lib/policy/page-context";
import { policyListQuerySchema } from "@/modules/policy";

export default async function PolicyListPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const { actor, service } = await policyPageContext();
  const query = policyListQuerySchema.parse({ keyword: typeof params.keyword === "string" ? params.keyword : undefined, level: typeof params.level === "string" ? params.level : undefined, tagId: typeof params.tagId === "string" ? params.tagId : undefined, effectStatus: typeof params.effectStatus === "string" ? params.effectStatus : undefined, page: typeof params.page === "string" ? params.page : undefined, pageSize: 20 });
  const [result, options] = await Promise.all([service.list({ actor, query }), service.formOptions({ actor })]);
  return <section><p className="text-sm text-blue-600">政策资源</p><h1 className="mt-1 text-2xl font-semibold">政策库</h1><form className="mt-5 grid gap-3 rounded-2xl bg-white p-4 shadow-sm"><input name="keyword" defaultValue={query.keyword} placeholder="搜索政策名称或发布部门" className="rounded-xl border border-slate-200 p-3"/><div className="grid grid-cols-2 gap-2"><select name="level" defaultValue={query.level} className="rounded-xl border border-slate-200 p-3"><option value="">全部层级</option>{options.levels.map((level) => <option key={level}>{level}</option>)}</select><select name="effectStatus" defaultValue={query.effectStatus} className="rounded-xl border border-slate-200 p-3"><option value="">全部效力</option><option value="CURRENT">现行</option><option value="REPLACED">已被替代</option></select></div><select name="tagId" defaultValue={query.tagId} className="rounded-xl border border-slate-200 p-3"><option value="">全部标签</option>{options.tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button className="rounded-xl bg-slate-900 p-3 text-white">查询</button></form><p className="mt-4 text-sm text-slate-500">共 {result.total} 条已发布政策</p><div className="mt-3 space-y-3">{result.items.length ? result.items.map((policy) => <Link key={policy.id} href={`/resources/policies/${policy.id}`} className="block rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{policy.title}</h2><span className={`shrink-0 rounded-full px-2 py-1 text-xs ${policy.effectStatus === "CURRENT" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{policy.effectStatus === "CURRENT" ? "现行" : "已被替代"}</span></div><p className="mt-2 text-sm text-slate-600">{policy.issuingDepartment} · {policy.publicationDate.toISOString().slice(0, 10)} · {policy.level}</p><div className="mt-3 flex flex-wrap gap-2">{policy.tags.map((tag) => <span key={tag.id} className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{tag.name}</span>)}</div></Link>) : <div className="rounded-2xl bg-white p-8 text-center text-slate-500">暂无符合条件的政策，请调整筛选条件。</div>}</div></section>;
}
