import Link from "next/link";
import { AttachmentOpenButton } from "@/components/policy/attachment-open-button";
import { AdminReimbursementActions, ExportButton } from "@/components/reimbursement/admin-reimbursement-actions";
import { reimbursementPageContext } from "@/lib/reimbursement/page-context";
import { REIMBURSEMENT_STATUS_LABELS } from "@/modules/reimbursement/constants";

type FrozenTrip = { title?: string; purpose?: string; nodes?: Array<{ sequenceNo: number; locationName: string; content: string; enterprise?: { name: string } | null }>; participants?: Array<{ person: { name: string } }> };

export default async function AdminReimbursementDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { actor, service } = await reimbursementPageContext(); const item = await service.detail({ actor, reimbursementId: id });
  const trip = item.currentSubmissionVersion?.tripSnapshotJson as FrozenTrip | null | undefined;
  const frozenExpenses = Array.isArray(item.currentSubmissionVersion?.expenseSnapshotJson) ? item.currentSubmissionVersion.expenseSnapshotJson as Array<{ id?: string; expenseType?: string; customExpenseName?: string | null; amount?: string }> : [];
  return <section><Link href="/reimbursement-admin" className="text-sm text-blue-600">‹ 返回报销管理</Link><header className="mt-5 rounded-2xl border bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-blue-600">{item.businessNo}</p><h2 className="mt-1 text-3xl font-semibold">{item.applicant.name}的{item.type === "TRAVEL" ? "出行" : "活动"}报销</h2></div><span>{REIMBURSEMENT_STATUS_LABELS[item.status]}</span></div><p className="mt-4 whitespace-pre-wrap">{item.currentSubmissionVersion?.reasonSnapshot ?? item.reason}</p><p className="mt-3 text-slate-500">金额：¥{item.currentSubmissionVersion?.totalAmount.toString() ?? item.totalAmount.toString()} · 当前提交版本：{item.currentSubmissionVersion?.versionNo ?? "尚未提交"}</p>{item.status === "FINANCE_SUBMITTED" && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">已提交财务 = 纸质材料已交财务，不代表财务审批或付款。</p>}<div className="mt-4"><ExportButton id={item.id}/></div></header>
    <AdminReimbursementActions id={item.id} status={item.status}/>
    {trip && <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-semibold">提交时行程快照</h3><p className="mt-3">{trip.title} · {trip.purpose}</p><p className="mt-2 text-sm text-slate-500">参与人员：{trip.participants?.map((x) => x.person.name).join("、") || "未记录"}</p>{trip.nodes?.map((node) => <p key={node.sequenceNo} className="mt-3 border-t pt-3 text-sm">{node.enterprise?.name ?? node.locationName} · {node.content}</p>)}</section>}
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">冻结费用明细</h3>{frozenExpenses.map((expense, index) => <p key={expense.id ?? index} className="mt-3 border-t pt-3 text-sm">{expense.customExpenseName ?? expense.expenseType} · ¥{expense.amount}</p>)}</section><section className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">票据与 OCR</h3>{item.invoices.map((invoice) => <div key={invoice.id} className="mt-3 border-t pt-3"><AttachmentOpenButton id={invoice.attachment.id} label={invoice.attachment.originalFilename}/><p className="mt-1 text-xs text-slate-500">{invoice.ocrStatus}{invoice.ocrWarning ? ` · ${invoice.ocrWarning}` : ""}</p>{invoice.confirmedInvoiceNo && <p className="mt-1 text-sm">发票号码：{invoice.confirmedInvoiceNo} · ¥{invoice.confirmedAmount?.toString() ?? "-"}</p>}</div>)}</section></div>
    <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-semibold">不可变提交版本</h3>{item.submissionVersions.map((version) => <p key={version.id} className="mt-3 border-t pt-3 text-sm">第 {version.versionNo} 版 · ¥{version.totalAmount.toString()} · {new Date(version.submittedAt).toLocaleString("zh-CN")}</p>)}</section>
    <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-semibold">流转与永久审计</h3>{item.timeline.map((event) => <p key={event.id} className="mt-3 border-t pt-3 text-sm">{event.actionCode} · {event.actorPerson?.name ?? "系统"} · {new Date(event.createdAt).toLocaleString("zh-CN")}{event.reason ? ` · ${event.reason}` : ""}</p>)}</section>
  </section>;
}
