import { expect,test,type Browser,type Page } from "@playwright/test"; import { getPrismaClient } from "@/lib/db/prisma"; import { e2eUsers,enterpriseE2e,seedAuthFixtures } from "./auth-fixtures";
test.describe.configure({mode:"serial"});test.setTimeout(120_000);
async function login(page:Page,user:{phone:string;password:string}){await page.goto("/login");await page.getByLabel("手机号").fill(user.phone);await page.getByLabel("密码",{exact:true}).fill(user.password);await Promise.all([page.waitForResponse(r=>r.url().endsWith("/api/v2/auth/login")),page.getByRole("button",{name:"登录"}).click()]);}
async function api(page:Page,url:string,body?:unknown,headers?:Record<string,string>){return page.evaluate(async({url,body,headers})=>{const response=await fetch(url,{method:body===undefined?"GET":"POST",headers:body===undefined?headers:{"content-type":"application/json",...headers},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,json:await response.json()};},{url,body,headers});}
async function create(page:Page,category="ACCOMMODATION",attachmentIds:string[]=[]){return api(page,"/api/v2/help-requests",{category,title:`E2E 求助 ${crypto.randomUUID()}`,description:"办事求助关键链路",urgency:"NORMAL",attachmentIds});}
async function createAsNormal(page:Page,category="ACCOMMODATION",attachmentIds:string[]=[]){await login(page,e2eUsers.normal);return create(page,category,attachmentIds);}
async function transferToA(page:Page,id:string){await page.context().clearCookies();await login(page,e2eUsers.admin);return api(page,`/api/v2/admin/help-requests/${id}/transfer-org`,{organizationId:enterpriseE2e.organizationId,reason:"转交安宜镇"});}
async function claimAsTownship(page:Page,id:string){await page.context().clearCookies();await login(page,e2eUsers.township);return api(page,`/api/v2/help-requests/${id}/claim`,{expectedCompleteAt:new Date(Date.now()+3_600_000).toISOString()},{"Idempotency-Key":crypto.randomUUID()});}
async function assignedToTownship(page:Page){const created=await createAsNormal(page);const id=created.json.data.id;await page.context().clearCookies();await login(page,e2eUsers.admin);const assigned=await api(page,`/api/v2/admin/help-requests/${id}/assign-person`,{personId:e2eUsers.township.personId,expectedCompleteAt:new Date(Date.now()+3_600_000).toISOString(),reason:"直接分派"});return{id,assigned};}
async function transitionNormalToAlumni(){const prisma=getPrismaClient();const changedAt=new Date();await prisma.roleAssignment.updateMany({where:{personId:e2eUsers.normal.personId,roleCode:"MEMBER_CURRENT",expiredAt:null},data:{expiredAt:changedAt}});await prisma.roleAssignment.create({data:{personId:e2eUsers.normal.personId,roleCode:"MEMBER_ALUMNI_PLATFORM",effectiveAt:changedAt,grantedByPersonId:e2eUsers.superAdmin.personId,reason:"E2E 模拟批次切换"}});await prisma.account.update({where:{id:e2eUsers.normal.accountId},data:{permissionVersion:{increment:1}}});}
test.beforeEach(async()=>{await seedAuthFixtures();});
test("01 current member creates an accommodation request",async({page})=>{const result=await createAsNormal(page);expect(result.status).toBe(201);expect(result.json.data).toMatchObject({category:"ACCOMMODATION",status:"PENDING",submitterPersonId:e2eUsers.normal.personId});expect(result.json.data.businessNo).toMatch(/^QZ-\d{4}-\d{6}$/);});
test("02 dining is a supported category",async({page})=>{const result=await createAsNormal(page,"DINING");expect(result.status).toBe(201);expect(result.json.data.category).toBe("DINING");});
test("03 alumni cannot create",async({page})=>{await login(page,e2eUsers.alumni);expect((await create(page)).status).toBe(403);});
test("04 an unrelated current member cannot see private help",async({page})=>{const item=await createAsNormal(page);await page.context().clearCookies();await login(page,e2eUsers.groupLeader);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}`)).status).toBe(404);});
test("05 admin sees pending help",async({page})=>{const item=await createAsNormal(page);await page.context().clearCookies();await login(page,e2eUsers.admin);const list=await api(page,"/api/v2/help-requests?status=PENDING");expect(list.status).toBe(200);expect(list.json.data.items).toEqual(expect.arrayContaining([expect.objectContaining({id:item.json.data.id})]));});
test("06 admin transfers pending help to township A",async({page})=>{const item=await createAsNormal(page);const result=await transferToA(page,item.json.data.id);expect(result.status).toBe(200);expect(result.json.data).toMatchObject({status:"PENDING",currentOwnerPersonId:null,transferredOrganizationId:enterpriseE2e.organizationId});});
test("07 township B cannot see township A transfer",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await page.context().clearCookies();await login(page,e2eUsers.groupLeader);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}`)).status).toBe(404);});
test("08 two current organization workers race and only one claims",async({browser,page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);const [a,b]=await claimantPages(browser);const results=await Promise.all([api(a,`/api/v2/help-requests/${item.json.data.id}/claim`,{expectedCompleteAt:new Date(Date.now()+3_600_000).toISOString()},{"Idempotency-Key":crypto.randomUUID()}),api(b,`/api/v2/help-requests/${item.json.data.id}/claim`,{expectedCompleteAt:new Date(Date.now()+3_600_000).toISOString()},{"Idempotency-Key":crypto.randomUUID()})]);expect(results.filter(x=>x.status===200)).toHaveLength(1);expect(results.filter(x=>x.status===409)).toHaveLength(1);await a.context().close();await b.context().close();});
test("09 first claim requires and records expected completion",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await page.context().clearCookies();await login(page,e2eUsers.township);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}/claim`,{}, {"Idempotency-Key":crypto.randomUUID()})).status).toBe(422);const result=await api(page,`/api/v2/help-requests/${item.json.data.id}/claim`,{expectedCompleteAt:new Date(Date.now()+3_600_000).toISOString()},{"Idempotency-Key":crypto.randomUUID()});expect(result.status).toBe(200);expect(result.json.data.expectedCompleteAt).toBeTruthy();});
test("10 owner appends progress",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);const result=await api(page,`/api/v2/help-requests/${item.json.data.id}/progress`,{content:"已联系酒店",nextStep:"确认房间",attachmentIds:[]});expect(result.status).toBe(201);expect(result.json.data.progresses).toEqual(expect.arrayContaining([expect.objectContaining({content:"已联系酒店"})]));});
test("11 non-owner cannot append progress",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);await page.context().clearCookies();await login(page,e2eUsers.normal);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}/progress`,{content:"越权进展",attachmentIds:[]})).status).toBe(403);});
test("12 owner completes with summary",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);const result=await api(page,`/api/v2/help-requests/${item.json.data.id}/complete`,{completionSummary:"住宿安排完成"});expect(result.status).toBe(200);expect(result.json.data.status).toBe("COMPLETED");});
test("13 submitter reopens completed help with reason",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);await api(page,`/api/v2/help-requests/${item.json.data.id}/complete`,{completionSummary:"已完成"});await page.context().clearCookies();await login(page,e2eUsers.normal);const result=await api(page,`/api/v2/help-requests/${item.json.data.id}/reopen`,{reason:"实际仍需协助"});expect(result.status).toBe(200);expect(result.json.data).toMatchObject({status:"IN_PROGRESS",reopenReason:"实际仍需协助"});});
test("14 original owner continues after reopen",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);await api(page,`/api/v2/help-requests/${item.json.data.id}/complete`,{completionSummary:"已完成"});await page.context().clearCookies();await login(page,e2eUsers.normal);await api(page,`/api/v2/help-requests/${item.json.data.id}/reopen`,{reason:"继续处理"});await page.context().clearCookies();await login(page,e2eUsers.township);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}/progress`,{content:"继续协调",attachmentIds:[]})).status).toBe(201);});
test("15 admin reassigns an in-progress request",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);await page.context().clearCookies();await login(page,e2eUsers.admin);const result=await api(page,`/api/v2/admin/help-requests/${item.json.data.id}/reassign`,{targetType:"PERSON",personId:e2eUsers.normal.personId,reason:"工作调整",expectedCompleteAt:new Date(Date.now()+7_200_000).toISOString()});expect(result.status).toBe(200);expect(result.json.data.currentOwnerPersonId).toBe(e2eUsers.normal.personId);});
test("16 submitter withdraws pending help",async({page})=>{const item=await createAsNormal(page);const result=await api(page,`/api/v2/help-requests/${item.json.data.id}/withdraw`,{reason:"计划取消"});expect(result.status).toBe(200);expect(result.json.data).toMatchObject({status:"WITHDRAWN",currentOwnerPersonId:null});});
test("17 submitter cannot withdraw in-progress help",async({page})=>{const{id}=await assignedToTownship(page);await page.context().clearCookies();await login(page,e2eUsers.normal);expect((await api(page,`/api/v2/help-requests/${id}/withdraw`,{reason:"处理中撤回"})).status).toBe(409);});
test("18 overdue is derived by expected completion",async({page})=>{const{id}=await assignedToTownship(page);await getPrismaClient().helpRequest.update({where:{id},data:{expectedCompleteAt:new Date(Date.now()-60_000)}});await page.context().clearCookies();await login(page,e2eUsers.normal);const result=await api(page,"/api/v2/help-requests?overdue=true");expect(result.status).toBe(200);expect(result.json.data.items).toEqual(expect.arrayContaining([expect.objectContaining({id,overdue:true})]));});
test("19 group leader and minister have no unrelated private visibility",async({page})=>{const item=await createAsNormal(page);for(const user of [e2eUsers.groupLeader,e2eUsers.minister]){await page.context().clearCookies();await login(page,user);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}`)).status).toBe(404);}});
test("20 attachment access follows the private help parent",async({page})=>{const prisma=getPrismaClient();const attachment=await prisma.attachment.create({data:{originalFilename:"E2E私密求助.pdf",extension:"pdf",declaredMimeType:"application/pdf",expectedSizeBytes:BigInt(8),actualSizeBytes:BigInt(8),bucket:"test",region:"test",objectKey:`help-e2e/${crypto.randomUUID()}.pdf`,uploadStatus:"UPLOADED",scanStatus:"PASSED",isTemporary:true,uploadedByPersonId:e2eUsers.normal.personId}});const item=await createAsNormal(page,"LIFE",[attachment.id]);expect(item.status).toBe(201);await page.context().clearCookies();await login(page,e2eUsers.minister);expect((await api(page,`/api/v2/attachments/${attachment.id}/access?action=preview`)).status).toBe(403);});
test("21 lifecycle intentionally emits no no-op outbox",async({page})=>{const item=await createAsNormal(page);await transferToA(page,item.json.data.id);expect(await getPrismaClient().outboxEvent.count({where:{aggregateType:"HELP_REQUEST",aggregateId:item.json.data.id}})).toBe(0);});
test("22 former owner loses detail, handled-list, and attachment access after reassignment",async({page})=>{const prisma=getPrismaClient();const attachment=await prisma.attachment.create({data:{originalFilename:"E2E历史处理人私密附件.pdf",extension:"pdf",declaredMimeType:"application/pdf",expectedSizeBytes:BigInt(8),actualSizeBytes:BigInt(8),bucket:"test",region:"test",objectKey:`help-e2e/${crypto.randomUUID()}.pdf`,uploadStatus:"UPLOADED",scanStatus:"PASSED",isTemporary:true,uploadedByPersonId:e2eUsers.normal.personId}});const item=await createAsNormal(page,"LIFE",[attachment.id]);await transferToA(page,item.json.data.id);await claimAsTownship(page,item.json.data.id);await page.context().clearCookies();await login(page,e2eUsers.admin);expect((await api(page,`/api/v2/admin/help-requests/${item.json.data.id}/reassign`,{targetType:"PERSON",personId:e2eUsers.township2.personId,reason:"更换主办人",expectedCompleteAt:new Date(Date.now()+7_200_000).toISOString()})).status).toBe(200);await prisma.appointment.updateMany({where:{personId:e2eUsers.township.personId,organizationId:enterpriseE2e.organizationId,expiredAt:null},data:{expiredAt:new Date()}});await page.context().clearCookies();await login(page,e2eUsers.township2);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}`)).status).toBe(200);await page.context().clearCookies();await login(page,e2eUsers.township);expect((await api(page,`/api/v2/help-requests/${item.json.data.id}`)).status).toBe(404);const handled=await api(page,"/api/v2/help-requests?mode=handled");expect(handled.status).toBe(200);expect(handled.json.data.items.map((x:{id:string})=>x.id)).not.toContain(item.json.data.id);expect((await api(page,`/api/v2/attachments/${attachment.id}/access?action=preview`)).status).toBe(403);expect(await prisma.helpAssignmentHistory.count({where:{helpRequestId:item.json.data.id,personId:e2eUsers.township.personId,assignmentType:"CLAIM",expiredAt:{not:null}}})).toBe(1);});
test("23 alumni submitter can withdraw an old pending Help but still cannot create",async({page})=>{const item=await createAsNormal(page);await transitionNormalToAlumni();await page.context().clearCookies();await login(page,e2eUsers.normal);expect((await create(page)).status).toBe(403);const withdrawn=await api(page,`/api/v2/help-requests/${item.json.data.id}/withdraw`,{reason:"批次变化后撤回"});expect(withdrawn.status).toBe(200);expect(withdrawn.json.data.status).toBe("WITHDRAWN");});
test("24 alumni submitter can reopen own completed Help but not another person's Help",async({page})=>{const{id}=await assignedToTownship(page);await page.context().clearCookies();await login(page,e2eUsers.township);expect((await api(page,`/api/v2/help-requests/${id}/complete`,{completionSummary:"已完成"})).status).toBe(200);await transitionNormalToAlumni();await page.context().clearCookies();await login(page,e2eUsers.alumni);expect((await api(page,`/api/v2/help-requests/${id}/reopen`,{reason:"越权重开"})).status).toBe(403);await page.context().clearCookies();await login(page,e2eUsers.normal);const reopened=await api(page,`/api/v2/help-requests/${id}/reopen`,{reason:"角色变化后仍需处理"});expect(reopened.status).toBe(200);expect(reopened.json.data.status).toBe("IN_PROGRESS");});
test("25 concurrent cross-Help reuse of one claim key returns one stable conflict",async({browser,page})=>{const first=await createAsNormal(page);const second=await create(page);await transferToA(page,first.json.data.id);await transferToA(page,second.json.data.id);const a=await browser.newPage();const b=await browser.newPage();await Promise.all([login(a,e2eUsers.township),login(b,e2eUsers.township)]);const key=crypto.randomUUID();const expectedCompleteAt=new Date(Date.now()+3_600_000).toISOString();const results=await Promise.all([api(a,`/api/v2/help-requests/${first.json.data.id}/claim`,{expectedCompleteAt},{"Idempotency-Key":key}),api(b,`/api/v2/help-requests/${second.json.data.id}/claim`,{expectedCompleteAt},{"Idempotency-Key":key})]);expect(results.filter(x=>x.status===200)).toHaveLength(1);const conflict=results.find(x=>x.status===409);expect(conflict?.json.error.code).toBe("HELP_IDEMPOTENCY_CONFLICT");await a.context().close();await b.context().close();});
async function claimantPages(browser:Browser){const a=await browser.newPage();const b=await browser.newPage();await Promise.all([login(a,e2eUsers.township),login(b,e2eUsers.township2)]);return[a,b] as const;}
