import { expect,test,type Page } from "@playwright/test"; import { getPrismaClient } from "@/lib/db/prisma"; import { e2eUsers,enterpriseE2e,seedAuthFixtures,talentE2e } from "./auth-fixtures";
test.describe.configure({mode:"serial"});
test.setTimeout(120_000);
async function login(page:Page,user:{phone:string;password:string}){await page.goto("/login");await page.getByLabel("手机号").fill(user.phone);await page.getByLabel("密码",{exact:true}).fill(user.password);await Promise.all([page.waitForResponse(r=>r.url().endsWith("/api/v2/auth/login")),page.getByRole("button",{name:"登录"}).click()]);}
async function api(page:Page,url:string,body?:unknown){return page.evaluate(async({url,body})=>{const response=await fetch(url,{method:body===undefined?"GET":"POST",headers:body===undefined?undefined:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,json:await response.json()};},{url,body});}
async function startRound(page:Page){return api(page,`/api/v2/talents/${talentE2e.talentId}/contact-rounds`,{areaId:enterpriseE2e.areaAId});}
test.beforeEach(async()=>{await seedAuthFixtures();});
test("01 resource entrance opens the talent list",async({page})=>{await login(page,e2eUsers.normal);await page.goto("/resources");await page.getByRole("link",{name:"人才库",exact:true}).click();await expect(page.getByRole("heading",{name:"人才库"})).toBeVisible();});
test("02 active talent appears in the mobile list",async({page})=>{await login(page,e2eUsers.normal);await page.goto("/resources/talents");await expect(page.getByRole("link",{name:/E2E 智能制造专家/})).toBeVisible();});
test("03 keyword search covers organization and direction",async({page})=>{await login(page,e2eUsers.normal);await page.goto("/resources/talents?keyword=工业软件");await expect(page.getByText("E2E 智能制造专家")).toBeVisible();await page.goto("/resources/talents?keyword=不存在方向");await expect(page.getByText("暂无符合条件的人才。")).toBeVisible();});
test("04 scope filter returns domestic talent",async({page})=>{await login(page,e2eUsers.normal);const result=await api(page,"/api/v2/talents?scopeType=DOMESTIC");expect(result.status).toBe(200);expect(result.json.data.items).toEqual(expect.arrayContaining([expect.objectContaining({id:talentE2e.talentId,scopeType:"DOMESTIC"})]));});
test("05 detail shows profile and achievements",async({page})=>{await login(page,e2eUsers.normal);await page.goto(`/resources/talents/${talentE2e.talentId}`);await expect(page.getByRole("heading",{name:"E2E 智能制造专家"})).toBeVisible();await expect(page.getByText("获得多项发明专利。")).toBeVisible();});
test("06 detail exposes only internal recommender and contact phone",async({page})=>{await login(page,e2eUsers.normal);const result=await api(page,`/api/v2/talents/${talentE2e.talentId}`);expect(result.status).toBe(200);expect(result.json.data.currentContactPerson.account.phone).toBe(e2eUsers.normal.phone);expect(result.json.data).not.toHaveProperty("phone");expect(result.json.data).not.toHaveProperty("email");});
test("07 member submits a create request",async({page})=>{await login(page,e2eUsers.normal);const result=await api(page,"/api/v2/talent-change-requests",{requestType:"CREATE",payload:{talent:{name:"E2E 新人才",scopeType:"OVERSEAS",organizationName:"海外研究院",title:"研究员",professionalDirection:"新能源"}},attachmentIds:[]});expect(result.status).toBe(201);expect(result.json.data.status).toBe("PENDING_REVIEW");});
test("08 alumni submits a create request",async({page})=>{await login(page,e2eUsers.alumni);const result=await api(page,"/api/v2/talent-change-requests",{requestType:"CREATE",payload:{talent:{name:"E2E 往届推荐",scopeType:"DOMESTIC",organizationName:"科研院",title:"专家",professionalDirection:"材料"}},attachmentIds:[]});expect(result.status).toBe(201);});
test("09 township submits a create request",async({page})=>{await login(page,e2eUsers.township);const result=await api(page,"/api/v2/talent-change-requests",{requestType:"CREATE",payload:{talent:{name:"E2E 镇街推荐",scopeType:"DOMESTIC",organizationName:"技术中心",title:"工程师",professionalDirection:"农业技术"}},attachmentIds:[]});expect(result.status).toBe(201);});
test("10 anonymous talent API is rejected",async({page})=>{await page.goto("/login");const result=await api(page,"/api/v2/talents");expect(result.status).toBe(401);});
test("11 ordinary member cannot enter talent administration",async({page})=>{await login(page,e2eUsers.normal);await page.goto("/admin/talents");await expect(page.getByRole("heading",{name:"当前账号不能进入管理后台"})).toBeVisible();});
test("12 ordinary member cannot merge talent",async({page})=>{await login(page,e2eUsers.normal);const result=await api(page,`/api/v2/admin/talents/${talentE2e.talentId}/merge`,{targetTalentId:crypto.randomUUID(),reason:"越权",confirmation:"CONFIRM"});expect(result.status).toBe(403);});
test("13 admin sees talent management list",async({page})=>{await login(page,e2eUsers.admin);await page.goto("/admin/talents");await expect(page.getByRole("heading",{name:"人才管理"})).toBeVisible();await expect(page.getByRole("link",{name:"E2E 智能制造专家"})).toBeVisible();});
test("14 admin detail shows append-only version history",async({page})=>{await login(page,e2eUsers.admin);await page.goto(`/admin/talents/${talentE2e.talentId}`);await expect(page.getByText("v1 · CREATE")).toBeVisible();});
test("15 admin changes current contact with a reason",async({page})=>{await login(page,e2eUsers.admin);const result=await api(page,`/api/v2/admin/talents/${talentE2e.talentId}/current-contact`,{personId:e2eUsers.minister.personId,reason:"工作调整"});expect(result.status).toBe(200);expect(result.json.data.currentContactPersonId).toBe(e2eUsers.minister.personId);});
test("16 township starts its first round",async({page})=>{await login(page,e2eUsers.township);const result=await startRound(page);expect(result.status).toBe(201);expect(result.json.data).toMatchObject({areaId:enterpriseE2e.areaAId,roundNo:1,status:"IN_PROGRESS"});});
test("17 township cannot start a round outside its area",async({page})=>{await login(page,e2eUsers.township);const result=await api(page,`/api/v2/talents/${talentE2e.talentId}/contact-rounds`,{areaId:enterpriseE2e.areaBId});expect(result.status).toBe(403);});
test("18 only one active round exists for the same talent and area",async({page})=>{await login(page,e2eUsers.township);expect((await startRound(page)).status).toBe(201);expect((await startRound(page)).status).toBe(409);});
test("19 current contact appends progress",async({page})=>{await login(page,e2eUsers.township);const round=(await startRound(page)).json.data;await page.context().clearCookies();await login(page,e2eUsers.normal);const result=await api(page,`/api/v2/talent-rounds/${round.id}/progress`,{content:"已建立联系",nextStep:"安排交流"});expect(result.status).toBe(201);});
test("20 current contact completes the round",async({page})=>{await login(page,e2eUsers.township);const round=(await startRound(page)).json.data;await page.context().clearCookies();await login(page,e2eUsers.normal);const result=await api(page,`/api/v2/talent-rounds/${round.id}/complete`,{resultSummary:"形成合作意向"});expect(result.status).toBe(200);expect(result.json.data.status).toBe("COMPLETED");expect((await api(page,`/api/v2/talent-rounds/${round.id}/progress`,{content:"终态追加"})).status).toBe(409);});
test("21 township withdraws a round with reason",async({page})=>{await login(page,e2eUsers.township);const round=(await startRound(page)).json.data;const result=await api(page,`/api/v2/talent-rounds/${round.id}/withdraw`,{reason:"暂不对接"});expect(result.status).toBe(200);expect(result.json.data.status).toBe("WITHDRAWN");});
test("22 admin review approves exactly one formal record",async({page})=>{await login(page,e2eUsers.normal);const submitted=await api(page,"/api/v2/talent-change-requests",{requestType:"CREATE",payload:{talent:{name:"E2E 审核人才",scopeType:"DOMESTIC",organizationName:"宝应人才测试院",title:"专家",professionalDirection:"智能制造"}},attachmentIds:[]});await page.context().clearCookies();await login(page,e2eUsers.admin);const reviewed=await api(page,`/api/v2/talent-change-requests/${submitted.json.data.id}/review`,{decision:"APPROVE",reason:"材料完整"});expect(reviewed.status).toBe(200);expect(reviewed.json.data.duplicateCandidates.length).toBeGreaterThan(0);const list=await api(page,"/api/v2/talents?keyword=E2E%20审核人才");expect(list.json.data.total).toBe(1);});
test("23 submitter confirms safe AI output and cannot confirm after approval",async({page})=>{const prisma=getPrismaClient();await prisma.attachment.create({data:{id:talentE2e.resumeAttachmentId,originalFilename:"E2E人才简历.pdf",extension:"pdf",declaredMimeType:"application/pdf",expectedSizeBytes:BigInt(10),actualSizeBytes:BigInt(10),bucket:"test-private",region:"ap-test",objectKey:"talent-e2e/resume.pdf",uploadStatus:"UPLOADED",scanStatus:"PASSED",isTemporary:true,uploadedByPersonId:e2eUsers.normal.personId}});await login(page,e2eUsers.normal);const submitted=await api(page,"/api/v2/talent-change-requests",{requestType:"CREATE",payload:{talent:{name:"E2E AI 人才",scopeType:"DOMESTIC",organizationName:"宝应人才测试院",title:"专家",professionalDirection:"智能制造"}},attachmentIds:[talentE2e.resumeAttachmentId]});expect(submitted.status).toBe(201);const extracted=await api(page,`/api/v2/talent-change-requests/${submitted.json.data.id}/ai-extract`,{attachmentId:talentE2e.resumeAttachmentId});expect(extracted.status).toBe(200);expect(extracted.json.data).toMatchObject({status:"COMPLETED",evidenceJson:{attachmentId:talentE2e.resumeAttachmentId}});const confirmed=await api(page,`/api/v2/talent-change-requests/${submitted.json.data.id}/ai-confirm`,{extractionId:extracted.json.data.id,workEducationExperience:"人工核对后的经历",representativeAchievements:"人工核对后的成果"});expect(confirmed.status).toBe(200);expect(confirmed.json.data.status).toBe("CONFIRMED");await page.context().clearCookies();await login(page,e2eUsers.admin);expect((await api(page,`/api/v2/talent-change-requests/${submitted.json.data.id}/review`,{decision:"APPROVE",reason:"材料完整"})).status).toBe(200);await page.context().clearCookies();await login(page,e2eUsers.normal);const repeated=await api(page,`/api/v2/talent-change-requests/${submitted.json.data.id}/ai-confirm`,{extractionId:extracted.json.data.id,workEducationExperience:"审批后漂移"});expect(repeated.status).toBe(409);expect(repeated.json.error.code).toBe("TALENT_REQUEST_STATE_CONFLICT");});
test("24 self-submitting admin retains reviewer governance",async({page})=>{const prisma=getPrismaClient();const submitted=await prisma.talentChangeRequest.create({data:{requestType:"CREATE",payloadSnapshot:{talent:{name:"E2E 智能制造专家",scopeType:"DOMESTIC",organizationName:"宝应人才测试院",title:"专家",professionalDirection:"智能制造"}},submitterPersonId:e2eUsers.admin.personId}});await login(page,e2eUsers.admin);await page.goto(`/admin/talent-change-requests/${submitted.id}`);await expect(page.getByText("重复候选（仅供人工核验，不自动合并）")).toBeVisible();await expect(page.getByRole("button",{name:"通过"})).toBeVisible();});
test("25 disabled accounts never appear in recommender or current-contact selectors",async({page})=>{await login(page,e2eUsers.admin);await page.goto("/admin/talents/new");await expect(page.locator("option",{hasText:"E2E disabled"})).toHaveCount(0);await page.goto(`/admin/talents/${talentE2e.talentId}`);await expect(page.locator("option",{hasText:"E2E disabled"})).toHaveCount(0);});
