import type { Prisma } from "@/generated/prisma/client";
import { getPrismaClient } from "@/lib/db/prisma";
import { authorizeActor } from "@/modules/permissions/authorization";
import type { PermissionActor } from "@/modules/permissions/types";
import { SystemError } from "./errors";
import { configEvaluationVersion } from "@/modules/ai/evaluation";
import { aiActivateSchema, aiConfigSchema } from "./schemas";
import type { SystemMutationContext } from "./types";
import { findSystemCommand, requireIdempotencyKey, saveSystemCommand, stableHash } from "./command";

export const AI_CAPABILITY_ALLOWLIST = ["CHAT", "DEMAND_CLASSIFY", "SIMILAR_DEMAND", "DEMAND_MATCH", "SIMILAR_TRIP", "POLICY_EXTRACT", "POLICY_INTERPRET", "POLICY_REPLACEMENT_SUGGEST", "TALENT_EXTRACT", "ENTERPRISE_TAG_SUGGEST", "INVOICE_OCR"] as const;
type Input = { actor: PermissionActor; context?: SystemMutationContext };
function safe<T extends { secretRef: string | null }>(config: T): Omit<T, "secretRef"> & { secretRef: string | null; secretConfigured: boolean; secretValue: undefined } { const { secretRef, ...rest } = config; return { ...rest, secretRef: secretRef ?? null, secretConfigured: Boolean(secretRef && process.env[secretRef]), secretValue: undefined }; }
function snapshot(value: unknown): Prisma.InputJsonValue { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }

export class AIConfigService {
  constructor(private readonly prisma = getPrismaClient()) {}
  async list(input: Input) { await authorizeActor({ actor: input.actor, action: "ai.metrics.view", resource: { resourceType: "ai-operation", requiredScope: "GLOBAL_OPERATIONAL" } }); const configs = await this.prisma.aIServiceConfig.findMany({ orderBy: { capability: "asc" } }); const counts = await this.prisma.demandRecommendationRun.groupBy({ by: ["status"], _count: { _all: true } }); return { allowlist: AI_CAPABILITY_ALLOWLIST, configs: configs.map(safe), metrics: { demandRecommendationRuns: counts.map((row) => ({ status: row.status, count: row._count._all })), privatePayloadsIncluded: false } }; }
  async saveDraft(input: Input & { body: unknown }) { await authorizeActor({ actor: input.actor, action: "ai.service.manage", resource: { resourceType: "ai-service-config", requiredScope: "SYSTEM" } }); const body = aiConfigSchema.parse(input.body); if (!AI_CAPABILITY_ALLOWLIST.includes(body.capability as (typeof AI_CAPABILITY_ALLOWLIST)[number])) throw new SystemError("AI_CONFIG_INVALID", "AI capability 不在正式白名单"); return this.prisma.$transaction(async (tx) => { const existing = await tx.aIServiceConfig.findUnique({ where: { capability: body.capability } }); const currentVersion = existing?.version ?? 0; if (currentVersion !== body.expectedVersion) throw new SystemError("AI_CONFIG_VERSION_CONFLICT", "AI 配置版本已变化", { expectedVersion: body.expectedVersion, currentVersion }); const next = currentVersion + 1; const data = { capability: body.capability, provider: body.provider, model: body.model, status: "DRAFT" as const, retentionPolicy: body.retentionPolicy, maxRetentionDays: body.maxRetentionDays ?? null, trainingOptOut: body.trainingOptOut, secretRef: body.secretRef ?? null, version: next, updatedByPersonId: input.actor.personId, lastTestStatus: "NOT_TESTED" as const, lastTestedAt: null, lastTestDurationMs: null, lastTestErrorCategory: null, evaluationVersion: null, evaluationPassedAt: null };
      const updated = existing ? await tx.aIServiceConfig.update({ where: { id: existing.id }, data }) : await tx.aIServiceConfig.create({ data }); const before = existing ? safe(existing) : null; const after = safe(updated); await tx.aIServiceConfigVersion.create({ data: { configId: updated.id, version: next, beforeJson: before ? snapshot(before) : undefined, afterJson: snapshot(after), reason: body.reason, changedByPersonId: input.actor.personId } }); await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: existing ? "AI_SERVICE_CONFIG_CHANGED" : "AI_SERVICE_CONFIG_CREATED", entityType: "AI_SERVICE_CONFIG", entityId: updated.id, beforeJson: before ? snapshot(before) : undefined, afterJson: snapshot(after), reason: body.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); return after; }); }
  async test(input: Input & { configId: string }) { await authorizeActor({ actor: input.actor, action: "ai.service.manage", resource: { resourceType: "ai-service-config", requiredScope: "SYSTEM" } }); const config = await this.prisma.aIServiceConfig.findUnique({ where: { id: input.configId } }); if (!config) throw new SystemError("AI_CONFIG_INVALID", "AI 配置不存在"); const started = Date.now(); const fakeEnabled = process.env.APP_ENV === "test" && process.env.ENABLE_FAKE_SYSTEM_PROVIDERS === "true"; const secretReady = Boolean(config.secretRef && process.env[config.secretRef]); const success = fakeEnabled && (secretReady || config.provider === "fake"); const duration = Date.now() - started; const updated = await this.prisma.aIServiceConfig.update({ where: { id: config.id }, data: { status: success ? "TESTED" : "DRAFT", lastTestedAt: new Date(), lastTestStatus: success ? "SUCCESS" : "FAILED", lastTestDurationMs: duration, lastTestErrorCategory: success ? null : "PROVIDER_NOT_CONFIGURED" } }); await this.prisma.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "AI_SERVICE_CONFIG_TESTED", entityType: "AI_SERVICE_CONFIG", entityId: config.id, afterJson: { capability: config.capability, provider: config.provider, model: config.model, durationMs: duration, result: success ? "SUCCESS" : "FAILED", payload: "SANITIZED_FIXED_MINIMAL" }, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); if (!success) throw new SystemError("AI_PROVIDER_UNAVAILABLE", "未配置可调用的 AI Provider；未读取任何真实业务正文"); return safe(updated); }
  async activate(input: Input & { configId: string; body: unknown; idempotencyKey: string | null }) { await authorizeActor({ actor: input.actor, action: "ai.service.manage", resource: { resourceType: "ai-service-config", requiredScope: "SYSTEM" } }); const body = aiActivateSchema.parse(input.body); const keyHash = requireIdempotencyKey(input.idempotencyKey); const payloadHash = stableHash({ configId: input.configId, body }); return this.prisma.$transaction(async (tx) => { const replay = await findSystemCommand(tx, { actorPersonId: input.actor.personId, action: "AI_CONFIG_ACTIVATE", keyHash, payloadHash }); if (replay) return replay.responseJson; await tx.$queryRaw`SELECT id FROM ai_service_configs WHERE id = ${input.configId} FOR UPDATE`; const config = await tx.aIServiceConfig.findUnique({ where: { id: input.configId } }); if (!config) throw new SystemError("AI_CONFIG_INVALID", "AI 配置不存在"); if (config.version !== body.expectedVersion) throw new SystemError("AI_CONFIG_VERSION_CONFLICT", "AI 配置版本已变化"); const expectedEvaluationVersion = configEvaluationVersion(config); if (config.lastTestStatus !== "SUCCESS" || !config.evaluationPassedAt || config.evaluationVersion !== expectedEvaluationVersion) throw new SystemError("AI_EVALUATION_REQUIRED", "激活前必须完成与当前配置严格绑定的固定评测"); const updated = await tx.aIServiceConfig.update({ where: { id: config.id }, data: { status: "ACTIVE", version: { increment: 1 } } }); await tx.aIServiceConfigVersion.create({ data: { configId: updated.id, version: updated.version, beforeJson: snapshot(safe(config)), afterJson: snapshot(safe(updated)), reason: body.reason, changedByPersonId: input.actor.personId } }); await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "AI_SERVICE_CONFIG_ACTIVATED", entityType: "AI_SERVICE_CONFIG", entityId: config.id, beforeJson: snapshot(safe(config)), afterJson: snapshot(safe(updated)), reason: body.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); const response = snapshot(safe(updated)); await saveSystemCommand(tx, { actorPersonId: input.actor.personId, action: "AI_CONFIG_ACTIVATE", keyHash, payloadHash, aggregateType: "AI_SERVICE_CONFIG", aggregateId: updated.id, response }); return safe(updated); }); }
}
