export const SYSTEM_ERROR_CODES = [
  "SYSTEM_SETTING_UNKNOWN", "SYSTEM_SETTING_READ_ONLY", "SYSTEM_SETTING_VERSION_CONFLICT",
  "WORK_CALENDAR_VERSION_CONFLICT", "SYSTEM_PREVIEW_STALE", "SYSTEM_IDEMPOTENCY_REQUIRED",
  "SYSTEM_IDEMPOTENCY_CONFLICT", "AI_CONFIG_INVALID", "AI_PROVIDER_UNAVAILABLE", "AI_TEST_FAILED",
  "AI_EVALUATION_REQUIRED", "AI_CONFIG_VERSION_CONFLICT", "BACKUP_PROVIDER_UNAVAILABLE",
  "BACKUP_NOT_FOUND", "BACKUP_NOT_READY", "RESTORE_NOT_FOUND", "RESTORE_PREVIEW_STALE",
  "RESTORE_CONFIRMATION_INVALID", "RESTORE_ACTIVE_CONFLICT", "RESTORE_MAINTENANCE_UNAVAILABLE",
  "RESTORE_PROVIDER_FAILED", "RESTORE_VALIDATION_FAILED",
] as const;

export type SystemErrorCode = (typeof SYSTEM_ERROR_CODES)[number];
const STATUS: Partial<Record<SystemErrorCode, number>> = {
  SYSTEM_SETTING_UNKNOWN: 404, SYSTEM_SETTING_READ_ONLY: 409, SYSTEM_SETTING_VERSION_CONFLICT: 409,
  WORK_CALENDAR_VERSION_CONFLICT: 409, SYSTEM_PREVIEW_STALE: 409, SYSTEM_IDEMPOTENCY_REQUIRED: 400,
  SYSTEM_IDEMPOTENCY_CONFLICT: 409, AI_CONFIG_INVALID: 422, AI_PROVIDER_UNAVAILABLE: 503,
  AI_TEST_FAILED: 502, AI_EVALUATION_REQUIRED: 409, AI_CONFIG_VERSION_CONFLICT: 409,
  BACKUP_PROVIDER_UNAVAILABLE: 503, BACKUP_NOT_FOUND: 404, BACKUP_NOT_READY: 409,
  RESTORE_NOT_FOUND: 404, RESTORE_PREVIEW_STALE: 409, RESTORE_CONFIRMATION_INVALID: 422,
  RESTORE_ACTIVE_CONFLICT: 409, RESTORE_MAINTENANCE_UNAVAILABLE: 503, RESTORE_PROVIDER_FAILED: 502,
  RESTORE_VALIDATION_FAILED: 409,
};

export class SystemError extends Error {
  readonly status: number;
  constructor(public readonly code: SystemErrorCode, message: string, public readonly details?: Record<string, unknown>) {
    super(message); this.name = "SystemError"; this.status = STATUS[code] ?? 400;
  }
}
export function isSystemError(error: unknown): error is SystemError { return error instanceof SystemError; }
