import { performance } from "node:perf_hooks";
import { getPrismaClient } from "@/lib/db/prisma";
import { authorizeActor } from "@/modules/permissions/authorization";
import type { PermissionActor } from "@/modules/permissions/types";
import { BackupService } from "./backup-service";
import { StorageHealthService } from "./storage-health-service";

export class HealthService {
  constructor(private readonly prisma = getPrismaClient(), private readonly backups = new BackupService(), private readonly storage = new StorageHealthService(prisma)) {}
  async overview(input: { actor: PermissionActor }) { await authorizeActor({ actor: input.actor, action: "system.health.view", resource: { resourceType: "system-overview", requiredScope: "SYSTEM" } }); const [failedJobs, unpublishedOutbox, missingBoundaries, failedAI, backup] = await Promise.all([this.prisma.jobTask.count({ where: { status: "FAILED" } }), this.prisma.outboxEvent.count({ where: { publishedAt: null } }), this.prisma.administrativeArea.count({ where: { status: "ACTIVE", boundaryVersions: { none: { isCurrent: true } } } }), this.prisma.aIServiceConfig.count({ where: { lastTestStatus: "FAILED" } }), this.backups.health()]); return { status: failedJobs || unpublishedOutbox > 100 || missingBoundaries || failedAI || backup.compliance !== "COMPLIANT" ? "DEGRADED" : "HEALTHY", alerts: { failedJobs, unpublishedOutbox, missingBoundaries, failedAI, backup: backup.compliance }, businessTimezone: "Asia/Shanghai", providerDetailsRestricted: true }; }
  async detail(input: { actor: PermissionActor }) { await authorizeActor({ actor: input.actor, action: "system.health.view", resource: { resourceType: "system-health", requiredScope: "SYSTEM" } }); const dbStart = performance.now(); await this.prisma.$queryRaw`SELECT 1`; const databaseLatencyMs = Math.round(performance.now() - dbStart); const now = new Date(); const [jobs, oldestWaiting, outbox, oldestOutbox, migrations, maps, storage, ai, backup] = await Promise.all([this.prisma.jobTask.groupBy({ by: ["status"], _count: { _all: true } }), this.prisma.jobTask.findFirst({ where: { status: "WAITING" }, orderBy: { scheduledAt: "asc" }, select: { scheduledAt: true } }), this.prisma.outboxEvent.count({ where: { publishedAt: null } }), this.prisma.outboxEvent.findFirst({ where: { publishedAt: null }, orderBy: { occurredAt: "asc" }, select: { occurredAt: true } }), this.prisma.migrationBatch.findFirst({ orderBy: { createdAt: "desc" }, select: { id: true, snapshotId: true, status: true, createdAt: true } }), Promise.all([this.prisma.administrativeArea.count({ where: { status: "ACTIVE", boundaryVersions: { none: { isCurrent: true } } } }), this.prisma.organization.count({ where: { status: "ACTIVE", type: "DISPATCH_UNIT", OR: [{ latitude: null }, { longitude: null }] } })]), this.storage.detail({ actor: input.actor }), this.prisma.aIServiceConfig.findMany({ select: { capability: true, provider: true, model: true, status: true, lastTestStatus: true, lastTestedAt: true, secretRef: true } }), this.backups.health()]);
    return { app: { service: "zhilianbao-v2", version: process.env.APP_VERSION ?? "UNKNOWN", uptimeSeconds: Math.round(process.uptime()), timezone: "Asia/Shanghai", now }, database: { status: "REACHABLE", latencyMs: databaseLatencyMs }, jobs: { counts: jobs, oldestWaitingAt: oldestWaiting?.scheduledAt ?? null }, outbox: { unpublished: outbox, oldestUnpublishedAt: oldestOutbox?.occurredAt ?? null }, migration: migrations ?? { status: "UNKNOWN" }, map: { areasWithoutBoundary: maps[0], dispatchOrganizationsWithoutCoordinate: maps[1] }, storage, ai: ai.map(({ secretRef, ...item }) => ({ ...item, secretConfigured: Boolean(secretRef && process.env[secretRef]) })), backup };
  }
}
