import { createHash } from "node:crypto";
import type { Prisma } from "@/generated/prisma/client"; import { getPrismaClient } from "@/lib/db/prisma";
import { authorizeActor } from "@/modules/permissions/authorization"; import type { PermissionActor } from "@/modules/permissions/types";
import type { BackupProvider } from "./backup-provider"; import { getBackupProvider } from "./backup-provider";
import { findSystemCommand, requireIdempotencyKey, saveSystemCommand, stableHash } from "./command"; import { SystemError } from "./errors";
import type { MaintenanceProvider } from "./maintenance-provider"; import { getMaintenanceProvider } from "./maintenance-provider";
import { RestoreValidationService } from "./restore-validation-service"; import { CURRENT_SCHEMA_VERSION, currentAppVersion, currentRuntimeEnvironment } from "./runtime";
import { restoreCompleteSchema, restoreConfirmSchema, restorePreviewSchema } from "./schemas"; import type { SystemMutationContext } from "./types";

type Input = { actor: PermissionActor; context?: SystemMutationContext };
type StoredPreview = { canConfirm?: boolean; providerPreviewReady?: boolean; target?: { provider?: string; sourceEnvironment?: string; backupSchemaVersion?: string }; current?: { appVersion?: string; runtimeEnvironment?: string; schemaMigrationVersion?: string } };
function auditJson(value: unknown): Prisma.InputJsonValue { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
export class RestoreService {
  constructor(private readonly prisma = getPrismaClient(), private readonly backup: BackupProvider = getBackupProvider(), private readonly maintenance: MaintenanceProvider = getMaintenanceProvider(), private readonly validator = new RestoreValidationService(prisma)) {}
  private assertBackupCompatible(record: { sourceEnvironment: string; provider: string; schemaVersion: string | null }, provider: string) {
    const runtime = currentRuntimeEnvironment(); if (record.sourceEnvironment !== runtime) throw new SystemError("RESTORE_CROSS_ENVIRONMENT_FORBIDDEN", "备份来源环境与当前运行环境不同", { sourceEnvironment: record.sourceEnvironment, runtimeEnvironment: runtime });
    if (record.provider !== provider) throw new SystemError("RESTORE_PROVIDER_MISMATCH", "当前 Provider 不支持恢复此备份", { backupProvider: record.provider, currentProvider: provider });
    if (record.schemaVersion !== CURRENT_SCHEMA_VERSION) throw new SystemError("RESTORE_SCHEMA_INCOMPATIBLE", "备份 schema 与当前要求版本不完全一致", { backupSchemaVersion: record.schemaVersion, currentSchemaVersion: CURRENT_SCHEMA_VERSION });
  }
  async preview(input: Input & { body: unknown }) {
    await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const body = restorePreviewSchema.parse(input.body); const record = await this.prisma.backupRecord.findUnique({ where: { id: body.backupRecordId } });
    if (!record) throw new SystemError("BACKUP_NOT_FOUND", "备份记录不存在"); if (record.status !== "SUCCEEDED" || !record.providerBackupId) throw new SystemError("BACKUP_NOT_READY", "只有成功且可定位的 Provider 备份可以预览恢复");
    const [backupHealth, maintenanceHealth, providerPreview, activeSessions, activeJobs, unpublishedOutbox, attachments, migration, activeRestore] = await Promise.all([this.backup.health(), this.maintenance.health(), this.backup.previewRestore(record.providerBackupId), this.prisma.session.count({ where: { expiresAt: { gt: new Date() }, revokedAt: null } }), this.prisma.jobTask.count({ where: { status: { in: ["WAITING", "RUNNING"] } } }), this.prisma.outboxEvent.count({ where: { publishedAt: null } }), this.prisma.attachment.count({ where: { isTemporary: false, uploadStatus: "UPLOADED", scanStatus: "PASSED" } }), this.prisma.migrationBatch.findFirst({ orderBy: { createdAt: "desc" }, select: { snapshotId: true } }), this.prisma.restoreRequest.findFirst({ where: { activeKey: "ACTIVE" }, select: { id: true } })]);
    if (activeRestore) throw new SystemError("RESTORE_ACTIVE_CONFLICT", "已有活动恢复请求", { restoreRequestId: activeRestore.id });
    const runtimeEnvironment = currentRuntimeEnvironment(); const appVersion = currentAppVersion(); const envMatches = record.sourceEnvironment === runtimeEnvironment; const providerMatches = record.provider === backupHealth.provider; const schemaMatches = record.schemaVersion === CURRENT_SCHEMA_VERSION;
    const canConfirm = backupHealth.ready && maintenanceHealth.ready && providerPreview.ready && envMatches && providerMatches && schemaMatches && appVersion !== "UNKNOWN";
    const preview = { target: { backupRecordId: record.id, snapshotAt: record.snapshotAt, backupType: record.backupType, sourceEnvironment: record.sourceEnvironment, provider: record.provider, backupSchemaVersion: record.schemaVersion }, current: { appVersion, runtimeEnvironment, schemaMigrationVersion: CURRENT_SCHEMA_VERSION, latestV1MigrationSnapshot: migration?.snapshotId ?? "UNKNOWN" }, estimatedDataLossWindow: record.snapshotAt ? { from: record.snapshotAt, to: new Date() } : "UNKNOWN", activeSessions, activeJobs, unpublishedOutbox, formalAttachmentBaseline: attachments, providerReadiness: backupHealth, providerPreviewReady: providerPreview.ready, maintenanceReadiness: maintenanceHealth, canConfirm, blockers: [!envMatches ? "RESTORE_CROSS_ENVIRONMENT_FORBIDDEN" : null, !providerMatches ? "RESTORE_PROVIDER_MISMATCH" : null, !schemaMatches ? "RESTORE_SCHEMA_INCOMPATIBLE" : null, appVersion === "UNKNOWN" ? "当前 appVersion 未知" : null, !backupHealth.ready ? "Backup Provider 不可用" : null, !maintenanceHealth.ready ? "Maintenance Provider 不可用" : null, !providerPreview.ready ? "Provider 不允许恢复" : null].filter(Boolean) };
    return this.prisma.$transaction(async (tx) => { const row = await tx.restoreRequest.create({ data: { backupRecordId: record.id, status: "PREVIEWED", reason: body.reason, previewVersion: 1, previewJson: auditJson(preview), requestedByPersonId: input.actor.personId } }); await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_PREVIEWED", entityType: "RESTORE_REQUEST", entityId: row.id, afterJson: auditJson({ backupRecordId: record.id, previewVersion: 1, canConfirm, blockers: preview.blockers }), reason: body.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); return { restoreRequestId: row.id, previewVersion: 1, ...preview }; });
  }
  async confirmAndStart(input: Input & { body: unknown; idempotencyKey: string | null }) {
    await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const body = restoreConfirmSchema.parse(input.body); const keyHash = requireIdempotencyKey(input.idempotencyKey); const payloadHash = stableHash(body);
    const preflight = await this.prisma.restoreRequest.findUnique({ where: { id: body.restoreRequestId }, include: { backupRecord: true } }); if (!preflight) throw new SystemError("RESTORE_NOT_FOUND", "恢复请求不存在");
    const [backupHealth, maintenanceHealth, providerPreview] = await Promise.all([this.backup.health(), this.maintenance.health(), preflight.backupRecord.providerBackupId ? this.backup.previewRestore(preflight.backupRecord.providerBackupId) : Promise.resolve({ ready: false })]);
    const stored = preflight.previewJson as StoredPreview | null; this.assertBackupCompatible(preflight.backupRecord, backupHealth.provider);
    if (!backupHealth.ready) throw new SystemError("BACKUP_PROVIDER_UNAVAILABLE", "Backup Provider 不可用"); if (!maintenanceHealth.ready) throw new SystemError("RESTORE_MAINTENANCE_UNAVAILABLE", "Maintenance Provider 不可用");
    if (!providerPreview.ready || stored?.providerPreviewReady !== providerPreview.ready || stored?.current?.appVersion !== currentAppVersion()) throw new SystemError("RESTORE_PREVIEW_STALE", "Provider readiness 或当前应用版本已变化，请重新预览");
    let restoreId: string;
    try { restoreId = await this.prisma.$transaction(async (tx) => { const replay = await findSystemCommand(tx, { actorPersonId: input.actor.personId, action: "RESTORE_START", keyHash, payloadHash }); if (replay) return (replay.responseJson as { restoreRequestId: string }).restoreRequestId;
      await tx.$queryRaw`SELECT id FROM restore_requests WHERE id = ${body.restoreRequestId} FOR UPDATE`; const restore = await tx.restoreRequest.findUnique({ where: { id: body.restoreRequestId }, include: { backupRecord: true } }); if (!restore || restore.status !== "PREVIEWED" || restore.previewVersion !== body.expectedPreviewVersion) throw new SystemError("RESTORE_PREVIEW_STALE", "恢复预览已失效");
      const preview = restore.previewJson as StoredPreview | null; if (!preview?.canConfirm || preview.current?.appVersion !== currentAppVersion() || preview.current?.runtimeEnvironment !== currentRuntimeEnvironment() || preview.current?.schemaMigrationVersion !== CURRENT_SCHEMA_VERSION) throw new SystemError("RESTORE_PREVIEW_STALE", "关键运行状态已变化，请重新预览");
      const phrase = `RESTORE ${restore.backupRecordId.slice(0, 8)}`; if (body.typedConfirmation !== phrase) throw new SystemError("RESTORE_CONFIRMATION_INVALID", "键入的恢复确认短语不正确");
      try { await tx.restoreRequest.update({ where: { id: restore.id }, data: { status: "CONFIRMED", activeKey: "ACTIVE", confirmedAt: new Date(), confirmationHash: createHash("sha256").update(body.typedConfirmation).digest("hex"), errorCode: null } }); } catch (error) { if (typeof error === "object" && error && "code" in error && error.code === "P2002") throw new SystemError("RESTORE_ACTIVE_CONFLICT", "已有活动恢复请求"); throw error; }
      await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_CONFIRMED", entityType: "RESTORE_REQUEST", entityId: restore.id, afterJson: { status: "CONFIRMED", previewVersion: restore.previewVersion, confirmationStoredAsHash: true }, reason: restore.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); const response = { restoreRequestId: restore.id } as Prisma.InputJsonValue; await saveSystemCommand(tx, { actorPersonId: input.actor.personId, action: "RESTORE_START", keyHash, payloadHash, aggregateType: "RESTORE_REQUEST", aggregateId: restore.id, response }); return restore.id; }); }
    catch (error) { if (!(typeof error === "object" && error && "code" in error && error.code === "P2002")) throw error; const replay = await this.prisma.systemCommandIdempotency.findUnique({ where: { actorPersonId_action_keyHash: { actorPersonId: input.actor.personId, action: "RESTORE_START", keyHash } } }); if (!replay || replay.payloadHash !== payloadHash) throw new SystemError("SYSTEM_IDEMPOTENCY_CONFLICT", "Idempotency-Key 已用于不同恢复命令"); restoreId = (replay.responseJson as { restoreRequestId: string }).restoreRequestId; }
    await this.ensureRestoreStarted({ ...input, restoreId }); return this.get({ ...input, restoreId });
  }
  async resumeStart(input: Input & { restoreId: string }) { await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); await this.ensureRestoreStarted(input); return this.get(input); }
  private async ensureRestoreStarted(input: Input & { restoreId: string }) {
    const restore = await this.prisma.restoreRequest.findUnique({ where: { id: input.restoreId }, include: { backupRecord: true, maintenanceEvents: true } }); if (!restore) throw new SystemError("RESTORE_NOT_FOUND", "恢复请求不存在");
    if (["EXECUTING", "PROVIDER_SUCCEEDED", "VALIDATION_REQUIRED", "SUCCEEDED"].includes(restore.status)) return restore; if (restore.status !== "CONFIRMED" || restore.providerOperationId) throw new SystemError("RESTORE_PREVIEW_STALE", "恢复状态不允许续跑");
    const health = await this.backup.health(); this.assertBackupCompatible(restore.backupRecord, health.provider); if (!health.ready) throw new SystemError("BACKUP_PROVIDER_UNAVAILABLE", "Backup Provider 不可用");
    const operationKey = `restore:${restore.id}:${restore.previewVersion}`;
    try {
      await this.maintenance.enter({ operationId: operationKey, reason: restore.reason });
      if (!restore.maintenanceEvents.some((event) => event.eventType === "ENTER" && event.operationId === operationKey)) await this.prisma.systemMaintenanceEvent.create({ data: { eventType: "ENTER", operationId: operationKey, restoreId: restore.id, actorPersonId: input.actor.personId, reason: restore.reason } });
      const operation = await this.backup.startRestore(restore.backupRecord.providerBackupId!, operationKey);
      return this.prisma.$transaction(async (tx) => { await tx.$queryRaw`SELECT id FROM restore_requests WHERE id = ${restore.id} FOR UPDATE`; const current = await tx.restoreRequest.findUniqueOrThrow({ where: { id: restore.id } }); if (current.providerOperationId) return current; const updated = await tx.restoreRequest.update({ where: { id: restore.id }, data: { status: "EXECUTING", startedAt: current.startedAt ?? new Date(), providerOperationId: operation.operationId, errorCode: null } }); await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_STARTED", entityType: "RESTORE_REQUEST", entityId: restore.id, afterJson: { status: "EXECUTING", maintenanceOperationId: operationKey }, reason: restore.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); return updated; });
    } catch { await this.prisma.restoreRequest.update({ where: { id: restore.id }, data: { status: "CONFIRMED", errorCode: "RESTORE_START_RETRY_REQUIRED" } }); throw new SystemError("RESTORE_PROVIDER_FAILED", "恢复启动结果未知；维护模式保持，使用同一操作继续启动"); }
  }
  async get(input: Input & { restoreId: string }) { await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const row = await this.prisma.restoreRequest.findUnique({ where: { id: input.restoreId }, include: { backupRecord: true, maintenanceEvents: { orderBy: { createdAt: "desc" } } } }); if (!row) throw new SystemError("RESTORE_NOT_FOUND", "恢复请求不存在"); return { ...row, maintenanceStatus: await this.maintenance.status() }; }
  async latest(input: Input) { await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const row = await this.prisma.restoreRequest.findFirst({ include: { backupRecord: true }, orderBy: { requestedAt: "desc" } }); return row ? { ...row, maintenanceStatus: await this.maintenance.status() } : null; }
  async validate(input: Input & { restoreId: string }) {
    await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const restore = await this.prisma.restoreRequest.findUnique({ where: { id: input.restoreId } }); if (restore?.status === "VALIDATION_REQUIRED") return restore; if (!restore?.providerOperationId || !["EXECUTING", "PROVIDER_SUCCEEDED"].includes(restore.status)) throw new SystemError("RESTORE_NOT_FOUND", "恢复操作不存在或状态不允许校验");
    const status = await this.backup.getRestoreStatus(restore.providerOperationId); if (status.status === "RUNNING") return restore;
    if (status.status === "FAILED") { await this.prisma.restoreRequest.update({ where: { id: restore.id }, data: { status: "FAILED", errorCode: status.errorCode ?? "RESTORE_PROVIDER_FAILED", finishedAt: new Date() } }); throw new SystemError("RESTORE_PROVIDER_FAILED", "Provider 恢复失败；维护模式保持不变"); }
    await this.prisma.$transaction([this.prisma.restoreRequest.update({ where: { id: restore.id }, data: { status: "PROVIDER_SUCCEEDED" } }), this.prisma.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_PROVIDER_SUCCEEDED", entityType: "RESTORE_REQUEST", entityId: restore.id, afterJson: { status: "PROVIDER_SUCCEEDED", businessValidationRequired: true }, reason: restore.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } })]); const validation = await this.validator.run(); const nextStatus = validation.passed ? "VALIDATION_REQUIRED" : "FAILED";
    const [updated] = await this.prisma.$transaction([this.prisma.restoreRequest.update({ where: { id: restore.id }, data: { status: nextStatus, validationJson: auditJson(validation), errorCode: validation.passed ? null : "RESTORE_VALIDATION_FAILED", finishedAt: validation.passed ? undefined : new Date() } }), this.prisma.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_VALIDATION_COMPLETED", entityType: "RESTORE_REQUEST", entityId: restore.id, afterJson: auditJson({ ...validation, maintenanceReleased: false }), reason: restore.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } })]); if (!validation.passed) throw new SystemError("RESTORE_VALIDATION_FAILED", "恢复后自动校验失败；维护模式保持不变"); return updated;
  }
  async complete(input: Input & { restoreId: string; body: unknown }) {
    await authorizeActor({ actor: input.actor, action: "backup.restore", resource: { resourceType: "restore", requiredScope: "SYSTEM" } }); const body = restoreCompleteSchema.parse(input.body); const restore = await this.prisma.restoreRequest.findUnique({ where: { id: input.restoreId } }); if (!restore) throw new SystemError("RESTORE_NOT_FOUND", "恢复请求不存在"); if (restore.status === "SUCCEEDED") return restore; if (restore.status !== "VALIDATION_REQUIRED") throw new SystemError("RESTORE_VALIDATION_FAILED", "恢复尚未通过自动校验与人工抽查");
    const operationKey = `restore:${restore.id}:${restore.previewVersion}`; const maintenance = await this.maintenance.status(); if (maintenance.active && maintenance.operationId === operationKey) await this.maintenance.exit(operationKey); else if (maintenance.completedOperationId !== operationKey) throw new SystemError("RESTORE_MAINTENANCE_UNAVAILABLE", "维护模式状态与恢复操作不一致，禁止完成");
    await this.prisma.session.deleteMany();
    return this.prisma.$transaction(async (tx) => { const existingExit = await tx.systemMaintenanceEvent.findFirst({ where: { restoreId: restore.id, operationId: operationKey, eventType: "EXIT" } }); if (!existingExit) await tx.systemMaintenanceEvent.create({ data: { eventType: "EXIT", operationId: operationKey, restoreId: restore.id, actorPersonId: input.actor.personId, reason: body.reason } }); const updated = await tx.restoreRequest.update({ where: { id: restore.id }, data: { status: "SUCCEEDED", activeKey: null, finishedAt: new Date() } }); await tx.auditLog.create({ data: { actorPersonId: input.actor.personId, actorAccountId: input.actor.accountId, actionCode: "RESTORE_COMPLETED", entityType: "RESTORE_REQUEST", entityId: restore.id, afterJson: { status: "SUCCEEDED", sessionsInvalidated: true, maintenanceReleased: true }, reason: body.reason, requestId: input.context?.requestId, ip: input.context?.ip, device: input.context?.deviceName } }); return updated; });
  }
}
