import { notFound } from "next/navigation";
import { AttachmentOpenButton } from "@/components/policy/attachment-open-button";
import { PolicyGovernanceActions, PolicyInterpretationForm, PolicyVersionForm } from "@/components/policy/admin-policy-forms";
import { policyPageContext } from "@/lib/policy/page-context";
import { PolicyError } from "@/modules/policy";

export default async function AdminPolicyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { actor, service } = await policyPageContext(); const id = (await params).id; let policy;
  try { policy = await service.detail({ actor, policyId: id }); } catch (error) { if (error instanceof PolicyError && error.status === 404) notFound(); throw error; }
  const [options, published] = await Promise.all([service.formOptions({ actor }), service.list({ actor, query: { publicationStatus: "PUBLISHED", effectStatus: "CURRENT", page: 1, pageSize: 100 } })]);
  const current = policy.versions.find((version) => version.id === policy.currentVersionId); if (!current) notFound();
  const latestCandidate = current.interpretations.find((item) => item.status === "COMPLETED"); const snapshot = current.snapshotJson as { interpretation?: Record<string, unknown> }; const candidate = latestCandidate?.extractedJson as Record<string, unknown> | null;
  const core = { title: policy.title, issuingDepartment: policy.issuingDepartment, publicationDate: policy.publicationDate.toISOString().slice(0, 10), level: policy.level, applicationDeadline: policy.applicationDeadline?.toISOString().slice(0, 10) ?? null, tagIds: policy.tags.map(({ id: tagId }) => tagId) };
  const activeRelations = [...policy.replacementsAsNew.filter((relation) => !relation.endedAt).map((relation) => ({ id: relation.id, label: `${policy.title} 替代 ${relation.oldPolicy.title}` })), ...policy.replacementsAsOld.filter((relation) => !relation.endedAt).map((relation) => ({ id: relation.id, label: `${relation.newPolicy.title} 替代 ${policy.title}` }))];
  const scanning = current.attachments.some(({ scanStatus }) => scanStatus === "PENDING" || scanStatus === "SCANNING");
  return <section className="space-y-6"><header><p className="text-sm text-blue-600">政策详情</p><h1 className="mt-1 text-3xl font-semibold">{policy.title}</h1><p className="mt-2 text-sm text-slate-500">{policy.issuingDepartment} · {core.publicationDate} · {policy.level} · {policy.publicationStatus}/{policy.effectStatus}</p></header><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">当前版本 v{current.versionNo}</h2><div className="mt-3 space-y-2 text-sm">{current.attachments.map((file) => <p key={file.id}><span className="mr-2 rounded bg-slate-100 px-2 py-1 text-xs">{file.relationType}</span><AttachmentOpenButton id={file.id} label={file.filename}/>{(file.scanStatus === "PENDING" || file.scanStatus === "SCANNING") && <span className="ml-2 text-xs text-amber-700">安全扫描中</span>}</p>)}</div>{scanning && <p role="status" className="mt-3 text-sm text-amber-700">安全扫描中，全部附件通过后才可发布或执行 AI 提取。</p>}<p className="mt-3 text-xs text-slate-500">核心字段：{current.coreFieldsConfirmedAt ? `已由管理员确认 ${current.coreFieldsConfirmedAt.toISOString()}` : "尚未人工确认"}</p></section>{policy.publicationStatus === "DRAFT" && <>{current.coreFieldsConfirmedAt ? <section className="rounded-2xl border border-blue-100 bg-blue-50/50 p-5 text-sm text-blue-800">当前版本已人工确认，如需修改请建立新内容版本。</section> : <PolicyInterpretationForm policyId={policy.id} core={core} tags={options.tags.map(({ id: tagId, name }) => ({ id: tagId, name }))} interpretationId={latestCandidate?.id} candidate={candidate ?? snapshot.interpretation}/>}<PolicyVersionForm policyId={policy.id} tags={options.tags.map(({ id: tagId, name }) => ({ id: tagId, name }))} defaults={core}/></>}<section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">版本历史</h2><div className="mt-3 space-y-2">{policy.versions.map((version) => <div key={version.id} className="rounded-xl bg-slate-50 p-3 text-sm">v{version.versionNo} · {version.createdAt.toISOString()} · {version.changeReason || "初始版本"} · 附件 {version.attachments.length} 个</div>)}</div></section><PolicyGovernanceActions id={policy.id} publicationStatus={policy.publicationStatus} effectStatus={policy.effectStatus} publishedPolicies={published.items.map((item) => ({ id: item.id, name: item.title }))} activeRelations={activeRelations}/></section>;
}
