import Link from "next/link";
import { AttachmentOpenButton } from "@/components/policy/attachment-open-button";
import { InvoiceConfirmForm, ReimbursementActions } from "@/components/reimbursement/reimbursement-actions";
import { reimbursementPageContext } from "@/lib/reimbursement/page-context";
import { REIMBURSEMENT_STATUS_LABELS } from "@/modules/reimbursement/constants";

type TripView = { title?: string; purpose?: string; overallEndAt?: string | Date | null; nodes?: Array<{ sequenceNo: number; plannedStartAt: string | Date; locationName: string; address?: string | null; content: string; enterprise?: { name: string } | null }>; participants?: Array<{ person: { name: string } }> };
const actionLabels: Record<string, string> = { REIMBURSEMENT_CREATED: "创建", REIMBURSEMENT_UPDATED: "修改草稿", REIMBURSEMENT_SUBMITTED: "提交线上核对", REIMBURSEMENT_WITHDRAWN: "撤回", REIMBURSEMENT_RETURNED: "退回修改", REIMBURSEMENT_VERIFIED: "线上核对完成", REIMBURSEMENT_PAPER_RECEIVED: "收到纸质材料", REIMBURSEMENT_PAPER_INCOMPLETE: "纸质材料不完整", REIMBURSEMENT_FINANCE_SUBMITTED: "提交财务", REIMBURSEMENT_STATE_CORRECTED: "状态纠正" };

function TripSection({ trip, frozen }: { trip: TripView; frozen: boolean }) {
  return <section className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">{frozen ? "提交时行程快照" : "关联行程"}</h2><p className="mt-3 text-sm">{trip.title} · {trip.overallEndAt ? new Date(trip.overallEndAt).toLocaleDateString("zh-CN") : ""}</p><p className="mt-2 text-sm text-slate-600">工作内容：{trip.purpose}</p><p className="mt-2 text-sm text-slate-600">参与人员：{trip.participants?.map((x) => x.person.name).join("、") || "未记录"}</p>{trip.nodes?.map((node) => <div key={node.sequenceNo} className="mt-3 border-t pt-3 text-sm"><strong>{node.enterprise?.name ?? node.locationName}</strong><p className="mt-1 text-slate-500">{new Date(node.plannedStartAt).toLocaleString("zh-CN")} · {node.address || node.locationName}</p><p className="mt-1">{node.content}</p></div>)}</section>;
}

export default async function ReimbursementDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { actor, service } = await reimbursementPageContext(); const item = await service.detail({ actor, reimbursementId: id });
  const mine = item.applicantPersonId === actor.personId; const editable = mine && (item.status === "DRAFT" || item.status === "RETURNED");
  const frozenTrip = item.currentSubmissionVersion?.tripSnapshotJson as TripView | null | undefined;
  return <article><Link href="/reimbursements" className="text-sm text-blue-600">‹ 返回报销</Link><header className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-sm text-blue-600">{item.businessNo}</p><h1 className="mt-1 text-2xl font-semibold">{item.type === "TRAVEL" ? "出行报销" : "活动报销"}</h1></div><span className="text-sm text-blue-700">{REIMBURSEMENT_STATUS_LABELS[item.status]}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{item.reason}</p><p className="mt-3 text-sm text-slate-500">申请人：{item.applicant.name} · 当前金额：¥{item.totalAmount.toString()}</p>{item.status === "FINANCE_SUBMITTED" && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">已提交财务 = 纸质材料已交财务，不代表财务审批或付款。</p>}{editable && <Link href={`/reimbursements/${item.id}/edit`} className="mt-4 inline-block rounded-lg border px-3 py-2 text-sm">编辑草稿</Link>}<ReimbursementActions id={item.id} status={item.status} editable={editable}/></header>
    {frozenTrip ? <TripSection trip={frozenTrip} frozen /> : item.linkedTrip ? <TripSection trip={item.linkedTrip} frozen={false} /> : null}
    <section className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">费用明细</h2>{item.expenses.map((expense) => <div key={expense.id} className="mt-3 flex justify-between border-t pt-3 text-sm"><span>{expense.customExpenseName ?? expense.expenseType}{expense.description ? ` · ${expense.description}` : ""}</span><strong>¥{expense.amount.toString()}</strong></div>)}{!item.expenses.length && <p className="mt-3 text-sm text-slate-500">暂无明细</p>}</section>
    <section className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">原票据与 OCR 结果</h2>{item.invoices.map((invoice) => <div key={invoice.id} className="mt-3 border-t pt-3"><AttachmentOpenButton id={invoice.attachment.id} label={invoice.attachment.originalFilename}/><p className="mt-2 text-xs text-slate-500">OCR：{invoice.ocrStatus}</p>{editable && invoice.ocrStatus !== "CONFIRMED" && <InvoiceConfirmForm reimbursementId={item.id} invoiceId={invoice.id} type={item.type} suggested={invoice.suggestedExpenseType} amount={invoice.confirmedAmount?.toString()} seller={invoice.confirmedSeller} invoiceNo={invoice.confirmedInvoiceNo} invoiceDate={invoice.confirmedInvoiceDate?.toISOString()} warning={invoice.ocrWarning} raw={invoice.ocrRawJson}/>}</div>)}{!item.invoices.length && <p className="mt-3 text-sm text-slate-500">暂无票据</p>}</section>
    {item.submissionVersions.length > 0 && <section className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">提交版本（不可变）</h2>{item.submissionVersions.map((version) => <p key={version.id} className="mt-3 border-t pt-3 text-sm">第 {version.versionNo} 版 · ¥{version.totalAmount.toString()} · {new Date(version.submittedAt).toLocaleString("zh-CN")}</p>)}</section>}
    <section className="mt-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">材料流转记录</h2>{item.timeline.map((event) => <div key={event.id} className="mt-3 border-t pt-3 text-sm"><p>{actionLabels[event.actionCode] ?? event.actionCode} · {event.actorPerson?.name ?? "系统"}</p><p className="mt-1 text-xs text-slate-500">{new Date(event.createdAt).toLocaleString("zh-CN")}{event.reason ? ` · ${event.reason}` : ""}</p></div>)}</section>
  </article>;
}
