export const TRIP_ENTITY = "TRIP";
export const TRIP_RESULT_ENTITY = "TRIP_RESULT";
export const ENTERPRISE_VISIT_ENTITY = "ENTERPRISE_VISIT";
export const TRIP_RESULT_ATTACHMENT_RELATION = "RESULT";
export const VISIT_ATTACHMENT_RELATION = "VISIT_MATERIAL";
