"use client";
import { type FormEvent, useState } from "react"; import { useRouter } from "next/navigation";
type Expense = { expenseType: string; amount: string; customExpenseName?: string; referenceRate?: string; claimedDays?: string; description?: string };
const travel = ["TRAVEL_TRANSPORT_ACTUAL", "TRAVEL_TRANSPORT_SUBSIDY", "TRAVEL_MEAL_SUBSIDY", "TRAVEL_LODGING"];
const activity = ["DINING", "VENUE", "MATERIAL_PRODUCTION", "SUPPLIES", "LODGING", "TRANSPORTATION", "OTHER"];
const labels: Record<string,string> = { TRAVEL_TRANSPORT_ACTUAL:"公共交通费实报实销",TRAVEL_TRANSPORT_SUBSIDY:"交通补贴",TRAVEL_MEAL_SUBSIDY:"伙食补贴",TRAVEL_LODGING:"住宿费",DINING:"餐饮",VENUE:"场地",MATERIAL_PRODUCTION:"物料制作",SUPPLIES:"用品",LODGING:"住宿",TRANSPORTATION:"交通",OTHER:"其他" };
async function api(url:string, method:string, body:unknown){const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error?.message??"保存失败");return result.data;}
export function ReimbursementForm({id,initial,trips}:{id?:string;initial?:{type:string;reason:string;linkedTripId:string|null;expenses:Expense[]};trips:{id:string;title:string}[]}) {
  const router=useRouter(); const [type,setType]=useState(initial?.type??"TRAVEL"); const [expenses,setExpenses]=useState<Expense[]>(initial?.expenses?.length?initial.expenses:[{expenseType:"TRAVEL_TRANSPORT_ACTUAL",amount:""}]); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
  const options=type==="TRAVEL"?travel:activity;
  function update(i:number,key:keyof Expense,value:string){setExpenses(items=>items.map((item,n)=>n===i?{...item,[key]:value}:item));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage("");try{const d=new FormData(event.currentTarget);const body={type,reason:String(d.get("reason")),linkedTripId:String(d.get("linkedTripId")||"")||null,expenses:expenses.map(e=>({expenseType:e.expenseType,amount:e.amount,customExpenseName:e.customExpenseName||undefined,description:e.description||undefined,source:"MANUAL",referenceRate:e.referenceRate||undefined,claimedDays:e.claimedDays||undefined}))};const item=await api(id?`/api/v2/reimbursements/${id}/update`:"/api/v2/reimbursements","POST",body);router.push(`/reimbursements/${item.id}`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"保存失败");}finally{setPending(false);}}
  return <form onSubmit={submit} className="space-y-4 rounded-2xl bg-white p-5 shadow-sm"><label className="block text-sm">报销类型<select value={type} onChange={e=>{const next=e.target.value;setType(next);setExpenses([{expenseType:next==="TRAVEL"?travel[0]:activity[0],amount:""}]);}} className="mt-1 w-full rounded-xl border p-3"><option value="TRAVEL">出行报销</option><option value="ACTIVITY">活动报销</option></select></label><label className="block text-sm">报销事由<textarea name="reason" required maxLength={2000} defaultValue={initial?.reason} rows={4} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm">关联已完成出行（可选）<select name="linkedTripId" defaultValue={initial?.linkedTripId??""} className="mt-1 w-full rounded-xl border p-3"><option value="">不关联</option>{trips.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><section><div className="flex items-center justify-between"><h2 className="font-medium">费用明细</h2><button type="button" onClick={()=>setExpenses(x=>[...x,{expenseType:options[0],amount:""}])} className="rounded-lg border px-3 py-1 text-sm">添加</button></div>{expenses.map((expense,i)=>{const subsidy=/SUBSIDY/.test(expense.expenseType);return <div key={i} className="mt-3 space-y-2 rounded-xl bg-slate-50 p-3"><select value={expense.expenseType} onChange={e=>update(i,"expenseType",e.target.value)} className="w-full rounded-lg border p-2">{options.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><input required inputMode="decimal" value={expense.amount} onChange={e=>update(i,"amount",e.target.value)} placeholder="金额" className="w-full rounded-lg border p-2"/>{expense.expenseType==="OTHER"&&<input required value={expense.customExpenseName??""} onChange={e=>update(i,"customExpenseName",e.target.value)} placeholder="其他费用名称" className="w-full rounded-lg border p-2"/>}{subsidy&&<div className="grid grid-cols-2 gap-2"><select required value={expense.referenceRate??""} onChange={e=>update(i,"referenceRate",e.target.value)} className="rounded-lg border p-2"><option value="">参考标准</option><option value="80">80 元</option><option value="100">100 元</option></select><input required inputMode="decimal" value={expense.claimedDays??""} onChange={e=>update(i,"claimedDays",e.target.value)} placeholder="申报天数" className="rounded-lg border p-2"/></div>}<input value={expense.description??""} onChange={e=>update(i,"description",e.target.value)} placeholder="说明（可选）" className="w-full rounded-lg border p-2"/><button type="button" onClick={()=>setExpenses(x=>x.filter((_,n)=>n!==i))} className="text-sm text-red-600">删除此项</button></div>})}</section><p className="text-xs leading-5 text-slate-500">交通/伙食补贴只允许手工按 80 或 100 元参考标准填写，不使用 OCR 或自动公式。</p>{message&&<p role="alert" className="text-sm text-red-600">{message}</p>}<button disabled={pending||!expenses.length} className="w-full rounded-xl bg-blue-600 p-3 font-medium text-white disabled:opacity-50">{pending?"保存中…":"保存草稿"}</button></form>;
}
