import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { getPrismaClient } from "@/lib/db/prisma";
import { MapService } from "@/modules/map/map-service";
import { resolveCapabilities, type PermissionActor } from "@/modules/permissions";

const prisma = getPrismaClient(); const personIds: string[] = []; const areaIds: string[] = []; const organizationIds: string[] = []; const enterpriseIds: string[] = []; const batchIds: string[] = [];
let actor: PermissionActor;
const polygon = (offset: number) => ({ type: "Feature", properties: { name: "TEST ONLY" }, geometry: { type: "Polygon", coordinates: [[[119.3 + offset, 33.2], [119.4 + offset, 33.2], [119.4 + offset, 33.3], [119.3 + offset, 33.2]]] } });
async function createPerson(name: string, role?: "MEMBER_CURRENT") { const person = await prisma.person.create({ data: { name: `M2-002 ${name} ${randomUUID()}` } }); personIds.push(person.id); const account = await prisma.account.create({ data: { personId: person.id, phone: `137${Math.floor(10000000 + Math.random() * 89999999)}`, passwordHash: "database-test-hash", status: "NORMAL" } }); if (role) await prisma.roleAssignment.create({ data: { personId: person.id, roleCode: role, effectiveAt: new Date("2026-01-01"), reason: "M2-002 TEST ONLY" } }); return { person, account }; }

beforeAll(async () => { const admin = await createPerson("admin"); await prisma.roleAssignment.create({ data: { personId: admin.person.id, roleCode: "ADMIN", effectiveAt: new Date("2026-01-01"), reason: "M2-002 TEST ONLY" } }); actor = { personId: admin.person.id, accountId: admin.account.id, accountStatus: "NORMAL", permissionVersion: BigInt(1), effectiveRoles: ["ADMIN"], capabilities: resolveCapabilities(["ADMIN"], new Set()), specialPermissions: new Set(), selfPersonId: admin.person.id, townshipAreaIds: [], departmentAreaIds: [], hasGlobalPublished: true, hasGlobalOperational: true, hasSystem: false, currentBatchMember: false, configurationIssues: [] }; });
afterAll(async () => { await prisma.auditLog.deleteMany({ where: { actorPersonId: { in: personIds } } }); await prisma.mapBoundaryVersion.deleteMany({ where: { areaId: { in: areaIds } } }); await prisma.enterprise.deleteMany({ where: { id: { in: enterpriseIds } } }); await prisma.batchMembership.deleteMany({ where: { OR: [{ personId: { in: personIds } }, { batchId: { in: batchIds } }] } }); await prisma.roleAssignment.deleteMany({ where: { personId: { in: personIds } } }); await prisma.account.deleteMany({ where: { personId: { in: personIds } } }); await prisma.person.deleteMany({ where: { id: { in: personIds } } }); await prisma.organization.deleteMany({ where: { id: { in: organizationIds } } }); await prisma.administrativeArea.deleteMany({ where: { id: { in: areaIds } } }); await prisma.batch.deleteMany({ where: { id: { in: batchIds } } }); await prisma.$disconnect(); });

describe("M2-002 real MySQL map invariants", () => {
  it("serializes concurrent version creation and boundary activation", async () => { const area = await prisma.administrativeArea.create({ data: { name: `TEST ONLY ${randomUUID()}`, type: "TOWNSHIP" } }); areaIds.push(area.id); const service = new MapService(prisma); const created = await Promise.all([service.createBoundary({ actor, boundary: { areaId: area.id, geoJson: polygon(0), reason: "TEST concurrent A" } }), service.createBoundary({ actor, boundary: { areaId: area.id, geoJson: polygon(0.01), reason: "TEST concurrent B" } })]); expect(new Set(created.map(({ versionNo }) => versionNo))).toEqual(new Set([1, 2])); await Promise.all(created.map((version) => service.activateBoundary({ actor, boundaryId: version.id, command: { reason: "TEST concurrent activate", confirmation: "ACTIVATE" } }))); expect(await prisma.mapBoundaryVersion.count({ where: { areaId: area.id, isCurrent: true } })).toBe(1); expect(await prisma.mapBoundaryVersion.count({ where: { areaId: area.id } })).toBe(2); expect(await prisma.auditLog.count({ where: { entityType: "MAP_BOUNDARY_VERSION", actionCode: "MAP_BOUNDARY_VERSION_ACTIVATED", actorPersonId: actor.personId } })).toBeGreaterThanOrEqual(2); });

  it("counts by formal responsibleAreaId and never invents marker coordinates", async () => { const area = await prisma.administrativeArea.create({ data: { name: `TEST enterprise area ${randomUUID()}`, type: "PARK" } }); areaIds.push(area.id); const located = await prisma.enterprise.create({ data: { name: `TEST located ${randomUUID()}`, responsibleAreaId: area.id, address: "TEST", mainProducts: "TEST", latitude: 33.2, longitude: 119.3, createdByPersonId: actor.personId } }); const unlocated = await prisma.enterprise.create({ data: { name: `TEST unlocated ${randomUUID()}`, responsibleAreaId: area.id, address: "TEST", mainProducts: "TEST", createdByPersonId: actor.personId } }); enterpriseIds.push(located.id, unlocated.id); const service = new MapService(prisma); const summary = await service.enterpriseAreas({ actor }); expect(summary.areas.find(({ id }) => id === area.id)?.count).toBe(2); const detail = await service.enterpriseAreaDetail({ actor, areaId: area.id, page: 1, pageSize: 100 }); expect(detail.enterprises.filter(({ hasValidCoordinate }) => hasValidCoordinate)).toHaveLength(1); expect(detail.enterprises.find(({ id }) => id === unlocated.id)).toMatchObject({ latitude: null, longitude: null, hasValidCoordinate: false }); });

  it("reuses member classification and groups unique Persons by dispatch unit", async () => { await prisma.batch.updateMany({ where: { isCurrent: true }, data: { isCurrent: false } }); const batch = await prisma.batch.create({ data: { name: `TEST map batch ${randomUUID()}`, year: 2026, startDate: new Date("2026-01-01"), endDate: new Date("2027-01-01"), status: "ACTIVE", isCurrent: true } }); batchIds.push(batch.id); const organization = await prisma.organization.create({ data: { name: `TEST dispatch ${randomUUID()}`, type: "DISPATCH_UNIT", latitude: 32.1, longitude: 118.7 } }); organizationIds.push(organization.id); const first = await createPerson("member A", "MEMBER_CURRENT"); const second = await createPerson("member B", "MEMBER_CURRENT"); await prisma.batchMembership.createMany({ data: [first, second].map(({ person }) => ({ personId: person.id, batchId: batch.id, dispatchOrganizationId: organization.id, startDate: new Date("2026-01-01"), endDate: new Date("2027-01-01"), status: "ACTIVE" })) }); const result = await new MapService(prisma).memberMap({ actor, query: { kind: "current" } }); const group = result.points.find(({ organization: item }) => item.id === organization.id); expect(group?.count).toBe(2); expect(new Set(group?.members.map(({ id }) => id)).size).toBe(2); });
});
