import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { RoleCode } from "@/generated/prisma/client";
import { getPrismaClient } from "@/lib/db/prisma";
import { MapService } from "@/modules/map/map-service";
import { resolveCapabilities, type PermissionActor } from "@/modules/permissions";

const prisma = getPrismaClient(); const personIds: string[] = []; const areaIds: string[] = []; const organizationIds: string[] = []; const enterpriseIds: string[] = []; const batchIds: string[] = [];
let actor: PermissionActor;
const polygon = (offset: number) => ({ type: "Feature", properties: { name: "TEST ONLY" }, geometry: { type: "Polygon", coordinates: [[[119.3 + offset, 33.2], [119.4 + offset, 33.2], [119.4 + offset, 33.3], [119.3 + offset, 33.2]]] } });
async function createPerson(name: string, role?: RoleCode) { const person = await prisma.person.create({ data: { name: `M2-002 ${name} ${randomUUID()}` } }); personIds.push(person.id); const account = await prisma.account.create({ data: { personId: person.id, phone: `137${Math.floor(10000000 + Math.random() * 89999999)}`, passwordHash: "database-test-hash", status: "NORMAL" } }); if (role) await prisma.roleAssignment.create({ data: { personId: person.id, roleCode: role, effectiveAt: new Date("2026-01-01"), reason: "M2-002 TEST ONLY" } }); return { person, account }; }

beforeAll(async () => { const admin = await createPerson("admin"); await prisma.roleAssignment.create({ data: { personId: admin.person.id, roleCode: "ADMIN", effectiveAt: new Date("2026-01-01"), reason: "M2-002 TEST ONLY" } }); actor = { personId: admin.person.id, accountId: admin.account.id, accountStatus: "NORMAL", permissionVersion: BigInt(1), effectiveRoles: ["ADMIN"], capabilities: resolveCapabilities(["ADMIN"], new Set()), specialPermissions: new Set(), selfPersonId: admin.person.id, townshipAreaIds: [], departmentAreaIds: [], hasGlobalPublished: true, hasGlobalOperational: true, hasSystem: false, currentBatchMember: false, configurationIssues: [] }; });
afterAll(async () => { await prisma.systemCommandIdempotency.deleteMany({ where: { actorPersonId: { in: personIds } } }); await prisma.auditLog.deleteMany({ where: { actorPersonId: { in: personIds } } }); await prisma.mapBoundaryVersion.deleteMany({ where: { areaId: { in: areaIds } } }); await prisma.enterprise.deleteMany({ where: { id: { in: enterpriseIds } } }); await prisma.batchMembership.deleteMany({ where: { OR: [{ personId: { in: personIds } }, { batchId: { in: batchIds } }] } }); await prisma.roleAssignment.deleteMany({ where: { personId: { in: personIds } } }); await prisma.account.deleteMany({ where: { personId: { in: personIds } } }); await prisma.person.deleteMany({ where: { id: { in: personIds } } }); await prisma.organization.deleteMany({ where: { id: { in: organizationIds } } }); await prisma.administrativeArea.deleteMany({ where: { id: { in: areaIds } } }); await prisma.batch.deleteMany({ where: { id: { in: batchIds } } }); await prisma.$disconnect(); });

describe("M2-002 real MySQL map invariants", () => {
  it("serializes concurrent version creation and boundary activation", async () => { const area = await prisma.administrativeArea.create({ data: { name: `TEST ONLY ${randomUUID()}`, type: "TOWNSHIP" } }); areaIds.push(area.id); const service = new MapService(prisma); const created = await Promise.all([service.createBoundary({ actor, boundary: { areaId: area.id, geoJson: polygon(0), reason: "TEST concurrent A" } }), service.createBoundary({ actor, boundary: { areaId: area.id, geoJson: polygon(0.01), reason: "TEST concurrent B" } })]); expect(new Set(created.map(({ versionNo }) => versionNo))).toEqual(new Set([1, 2])); const previews = await Promise.all(created.map((version) => service.activationPreview({ actor, boundaryId: version.id }))); await Promise.allSettled(created.map((version, index) => service.activateBoundary({ actor, boundaryId: version.id, command: { reason: "TEST concurrent activate", confirmation: "ACTIVATE", confirm: true, expectedCurrentBoundaryId: previews[index].expectedCurrentBoundaryId, expectedTargetVersion: previews[index].expectedTargetVersion, previewToken: previews[index].previewToken }, idempotencyKey: randomUUID() }))); expect(await prisma.mapBoundaryVersion.count({ where: { areaId: area.id, isCurrent: true } })).toBe(1); expect(await prisma.mapBoundaryVersion.count({ where: { areaId: area.id } })).toBe(2); expect(await prisma.auditLog.count({ where: { entityType: "MAP_BOUNDARY_VERSION", actionCode: "MAP_BOUNDARY_VERSION_ACTIVATED", actorPersonId: actor.personId } })).toBeGreaterThanOrEqual(1); });

  it("rejects activation after the locked area becomes inactive", async () => { const area = await prisma.administrativeArea.create({ data: { name: `TEST inactive area ${randomUUID()}`, type: "TOWNSHIP" } }); areaIds.push(area.id); const service = new MapService(prisma); const boundary = await service.createBoundary({ actor, boundary: { areaId: area.id, geoJson: polygon(0.02), reason: "TEST inactive gate" } }); const preview = await service.activationPreview({ actor, boundaryId: boundary.id }); await prisma.administrativeArea.update({ where: { id: area.id }, data: { status: "INACTIVE" } }); await expect(service.activateBoundary({ actor, boundaryId: boundary.id, command: { reason: "TEST must reject", confirmation: "ACTIVATE", confirm: true, expectedCurrentBoundaryId: preview.expectedCurrentBoundaryId, expectedTargetVersion: preview.expectedTargetVersion, previewToken: preview.previewToken }, idempotencyKey: randomUUID() })).rejects.toMatchObject({ code: "MAP_AREA_INACTIVE" }); expect(await prisma.mapBoundaryVersion.count({ where: { id: boundary.id, isCurrent: true } })).toBe(0); });

  it("counts by formal responsibleAreaId and never invents marker coordinates", async () => { const area = await prisma.administrativeArea.create({ data: { name: `TEST enterprise area ${randomUUID()}`, type: "PARK" } }); areaIds.push(area.id); const located = await prisma.enterprise.create({ data: { name: `TEST located ${randomUUID()}`, responsibleAreaId: area.id, address: "TEST", mainProducts: "TEST", latitude: 33.2, longitude: 119.3, createdByPersonId: actor.personId } }); const unlocated = await prisma.enterprise.create({ data: { name: `TEST unlocated ${randomUUID()}`, responsibleAreaId: area.id, address: "TEST", mainProducts: "TEST", createdByPersonId: actor.personId } }); enterpriseIds.push(located.id, unlocated.id); const service = new MapService(prisma); const summary = await service.enterpriseAreas({ actor }); expect(summary.areas.find(({ id }) => id === area.id)?.count).toBe(2); const detail = await service.enterpriseAreaDetail({ actor, areaId: area.id, page: 1, pageSize: 100 }); expect(detail.enterprises.filter(({ hasValidCoordinate }) => hasValidCoordinate)).toHaveLength(1); expect(detail.enterprises.find(({ id }) => id === unlocated.id)).toMatchObject({ latitude: null, longitude: null, hasValidCoordinate: false }); });

  it("restores every pre-existing Batch state and never maps alumni from future membership", async () => {
    const originalStates = await prisma.batch.findMany({ select: { id: true, isCurrent: true, status: true }, orderBy: { id: "asc" } });
    const testBatchIds: string[] = [];
    try {
      await prisma.batch.updateMany({ where: { isCurrent: true }, data: { isCurrent: false } });
      const current = await prisma.batch.create({ data: { name: `TEST current map batch ${randomUUID()}`, year: 2026, startDate: new Date("2026-01-01"), endDate: new Date("2027-01-01"), status: "ACTIVE", isCurrent: true } });
      const historical = await prisma.batch.create({ data: { name: `TEST historical map batch ${randomUUID()}`, year: 2025, startDate: new Date("2025-01-01"), endDate: new Date("2025-12-31"), status: "CLOSED", isCurrent: false } });
      const future = await prisma.batch.create({ data: { name: `TEST future map batch ${randomUUID()}`, year: 2099, startDate: new Date("2099-01-01"), endDate: new Date("2099-12-31"), status: "PLANNED", isCurrent: false } });
      testBatchIds.push(current.id, historical.id, future.id); batchIds.push(...testBatchIds);
      const currentOrganization = await prisma.organization.create({ data: { name: `TEST current dispatch ${randomUUID()}`, type: "DISPATCH_UNIT", latitude: 32.1, longitude: 118.7 } });
      const historicalOrganization = await prisma.organization.create({ data: { name: `TEST historical dispatch ${randomUUID()}`, type: "DISPATCH_UNIT", latitude: 32.2, longitude: 118.8 } });
      const futureOrganization = await prisma.organization.create({ data: { name: `TEST future dispatch ${randomUUID()}`, type: "DISPATCH_UNIT", latitude: 32.3, longitude: 118.9 } });
      organizationIds.push(currentOrganization.id, historicalOrganization.id, futureOrganization.id);
      const first = await createPerson("member A", "MEMBER_CURRENT"); const second = await createPerson("member B", "MEMBER_CURRENT");
      const alumniWithHistory = await createPerson("alumni history", "MEMBER_ALUMNI_PLATFORM"); const alumniFutureOnly = await createPerson("alumni future only", "MEMBER_ALUMNI_PLATFORM");
      await prisma.batchMembership.createMany({ data: [first, second].map(({ person }) => ({ personId: person.id, batchId: current.id, dispatchOrganizationId: currentOrganization.id, startDate: new Date("2026-01-01"), endDate: new Date("2027-01-01"), status: "ACTIVE" })) });
      await prisma.batchMembership.createMany({ data: [
        { personId: alumniWithHistory.person.id, batchId: historical.id, dispatchOrganizationId: historicalOrganization.id, startDate: new Date("2025-01-01"), endDate: new Date("2025-12-31"), status: "ENDED" },
        { personId: alumniWithHistory.person.id, batchId: future.id, dispatchOrganizationId: futureOrganization.id, startDate: new Date("2099-01-01"), endDate: new Date("2099-12-31"), status: "ACTIVE" },
        { personId: alumniFutureOnly.person.id, batchId: future.id, dispatchOrganizationId: futureOrganization.id, startDate: new Date("2099-01-01"), endDate: new Date("2099-12-31"), status: "ACTIVE" },
      ] });
      const service = new MapService(prisma); const currentResult = await service.memberMap({ actor, query: { kind: "current" } }); const currentGroup = currentResult.points.find(({ organization }) => organization.id === currentOrganization.id);
      expect(currentGroup?.count).toBe(2); expect(new Set(currentGroup?.members.map(({ id }) => id)).size).toBe(2);
      const alumniResult = await service.memberMap({ actor, query: { kind: "alumni", keyword: "M2-002 alumni" } });
      expect(alumniResult.points.find(({ organization }) => organization.id === historicalOrganization.id)?.members.map(({ id }) => id)).toContain(alumniWithHistory.person.id);
      expect(alumniResult.points.some(({ organization }) => organization.id === futureOrganization.id)).toBe(false);
      expect(alumniResult.unlocatedCount).toBe(1);
    } finally {
      await prisma.batchMembership.deleteMany({ where: { batchId: { in: testBatchIds } } });
      await prisma.batch.deleteMany({ where: { id: { in: testBatchIds } } });
      await Promise.all(originalStates.map((state) => prisma.batch.update({ where: { id: state.id }, data: { isCurrent: state.isCurrent, status: state.status } })));
    }
    const restoredStates = await prisma.batch.findMany({ where: { id: { in: originalStates.map(({ id }) => id) } }, select: { id: true, isCurrent: true, status: true }, orderBy: { id: "asc" } });
    expect(restoredStates).toEqual(originalStates);
  });

  it("rejects coordinate governance for an inactive dispatch organization", async () => { const organization = await prisma.organization.create({ data: { name: `TEST inactive dispatch ${randomUUID()}`, type: "DISPATCH_UNIT", status: "INACTIVE" } }); organizationIds.push(organization.id); await expect(new MapService(prisma).updateOrganizationCoordinate({ actor, organizationId: organization.id, coordinate: { latitude: 32.1, longitude: 118.7, reason: "TEST must reject" } })).rejects.toMatchObject({ code: "MAP_ORGANIZATION_INACTIVE" }); const unchanged = await prisma.organization.findUniqueOrThrow({ where: { id: organization.id }, select: { latitude: true, longitude: true } }); expect(unchanged).toEqual({ latitude: null, longitude: null }); });
});
