import Link from "next/link";
import { policyPageContext } from "@/lib/policy/page-context";
import { policyListQuerySchema } from "@/modules/policy";
import { businessLabel, policyEffectStatusLabel, policyPublicationStatusLabel } from "@/components/admin/business-labels";

export default async function AdminPoliciesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const { actor, service } = await policyPageContext();
  const query = policyListQuerySchema.parse({ keyword: typeof params.keyword === "string" ? params.keyword : undefined, publicationStatus: typeof params.publicationStatus === "string" ? params.publicationStatus : "PUBLISHED", effectStatus: typeof params.effectStatus === "string" ? params.effectStatus : undefined, page: typeof params.page === "string" ? params.page : undefined, pageSize: 20 });
  const result = await service.list({ actor, query });
  return <section><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-blue-600">资源管理</p><h1 className="mt-1 text-3xl font-semibold">政策治理</h1></div><Link href="/admin/policies/new" className="min-h-11 content-center rounded-xl bg-blue-600 px-4 py-2 text-white">新增政策</Link></div><form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input name="keyword" defaultValue={query.keyword} placeholder="名称/发布部门" className="rounded-xl border p-3"/><select name="publicationStatus" defaultValue={query.publicationStatus} className="rounded-xl border p-3"><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option><option value="WITHDRAWN">已撤回</option></select><select name="effectStatus" defaultValue={query.effectStatus} className="rounded-xl border p-3"><option value="">全部效力</option><option value="CURRENT">现行</option><option value="REPLACED">已被替代</option></select><button className="min-h-11 rounded-xl bg-slate-900 text-white">查询</button></form><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">政策</th><th className="p-4">发布部门/日期</th><th className="p-4">发布状态</th><th className="p-4">效力状态</th><th className="p-4">版本</th></tr></thead><tbody>{result.items.map((policy) => <tr key={policy.id} className="border-t"><td className="p-4"><Link href={`/admin/policies/${policy.id}`} className="font-medium text-blue-700">{policy.title}</Link><p className="mt-1 text-slate-500">{policy.level}</p></td><td className="p-4">{policy.issuingDepartment}<br/>{policy.publicationDate.toISOString().slice(0, 10)}</td><td className="p-4">{businessLabel(policyPublicationStatusLabel, policy.publicationStatus)}</td><td className="p-4">{businessLabel(policyEffectStatusLabel, policy.effectStatus)}</td><td className="p-4">v{policy.currentVersion?.versionNo ?? "—"}</td></tr>)}</tbody></table>{!result.items.length && <p className="p-8 text-center text-slate-500">暂无符合条件的政策。</p>}</div><p className="mt-3 text-sm text-slate-500">第 {result.page} 页，共 {result.total} 条</p></section>;
}
