import Link from "next/link";
import { demandLeadPageContext } from "@/lib/demand/page-context";
import { demandLeadListQuerySchema } from "@/modules/demand/schemas";

export default async function AdminDemandLeadPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const { actor, service } = await demandLeadPageContext();
  const query = demandLeadListQuerySchema.parse({ status: typeof params.status === "string" ? params.status : undefined, sourceType: typeof params.sourceType === "string" ? params.sourceType : undefined, areaId: typeof params.areaId === "string" ? params.areaId : undefined, keyword: typeof params.keyword === "string" ? params.keyword : undefined, page: typeof params.page === "string" ? params.page : undefined, pageSize: 20 });
  const result = await service.list({ actor, query });
  return <section><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-blue-600">M1-002 Demand Lead</p><h1 className="mt-1 text-3xl font-semibold">需求线索</h1></div><Link href="/admin/demand-leads/new" className="rounded-xl bg-blue-600 px-4 py-2 text-white">录入其他来源</Link></div><form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input name="keyword" defaultValue={query.keyword} placeholder="编号 / 企业 / 标题" className="rounded-xl border p-3"/><select name="status" defaultValue={query.status ?? ""} className="rounded-xl border p-3"><option value="">全部状态</option>{["PENDING_TOWNSHIP_VERIFY","PENDING_ENTERPRISE_LINK","NEED_MORE_INFO","MERGED","CLOSED","CONVERTED"].map((status) => <option key={status}>{status}</option>)}</select><select name="sourceType" defaultValue={query.sourceType ?? ""} className="rounded-xl border p-3"><option value="">全部来源</option><option value="ENTERPRISE_PUBLIC">公开提交</option><option value="MEMBER_VISIT">团员走访</option><option value="OTHER">其他</option></select><button className="rounded-xl bg-slate-900 text-white">查询</button></form><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">线索</th><th className="p-4">企业</th><th className="p-4">区域</th><th className="p-4">来源</th><th className="p-4">状态</th></tr></thead><tbody>{result.items.map((lead) => <tr key={lead.id} className="border-t"><td className="p-4"><Link className="font-medium text-blue-700" href={`/admin/demand-leads/${lead.id}`}>{lead.businessNo}</Link><p className="mt-1 max-w-sm truncate text-slate-600">{lead.rawTitle}</p></td><td className="p-4">{lead.rawEnterpriseName ?? lead.enterprise?.name ?? "—"}</td><td className="p-4">{lead.responsibleArea.name}</td><td className="p-4">{lead.sourceType}</td><td className="p-4">{lead.status}</td></tr>)}</tbody></table>{result.items.length === 0 && <p className="p-8 text-center text-slate-500">暂无符合条件的线索。</p>}</div><p className="mt-3 text-sm text-slate-500">第 {result.page} 页，共 {result.total} 条</p></section>;
}
