"use client";

import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { uploadAttachmentToCos, type BrowserUploadIntent } from "@/modules/attachment/client/cos-browser-uploader";

type Candidate = { workEducationExperience?: string; representativeAchievements?: string };
type Submitted = { requestId: string; attachmentId?: string; extractionId?: string; candidate?: Candidate };

async function api(url: string, body: unknown) {
  const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok || !result.ok) throw new Error(result.error?.message ?? "操作失败");
  return result.data;
}
async function fileBase64(file: File) { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (let offset = 0; offset < bytes.length; offset += 8192) binary += String.fromCharCode(...bytes.subarray(offset, offset + 8192)); return btoa(binary); }
async function upload(file: File) { const intent = await api("/api/v2/attachments/upload-intent", { filename: file.name, declaredMimeType: file.type || "application/octet-stream", expectedSizeBytes: file.size }) as BrowserUploadIntent & { attachmentId: string }; if (intent.upload.type === "TEST_MEMORY") await api(`/api/v2/test/attachments/${intent.attachmentId}/upload`, { base64: await fileBase64(file) }); else await uploadAttachmentToCos(intent, file).promise; await api(`/api/v2/attachments/${intent.attachmentId}/complete`, {}); if (intent.upload.type === "TEST_MEMORY") await api(`/api/v2/test/attachments/${intent.attachmentId}/scan`, {}); return intent.attachmentId; }

export function TalentSubmitForm({ people }: { people: { id: string; name: string }[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [submitted, setSubmitted] = useState<Submitted>();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const formData = new FormData(event.currentTarget); try { const resume = formData.get("resume"); const attachmentId = resume instanceof File && resume.size > 0 ? await upload(resume) : undefined; const talent = { name: String(formData.get("name")), scopeType: String(formData.get("scopeType")), organizationName: String(formData.get("organizationName")), title: String(formData.get("title")), professionalDirection: String(formData.get("professionalDirection")), originalRecommenderPersonId: String(formData.get("originalRecommenderPersonId") || "") || undefined, workEducationExperience: String(formData.get("workEducationExperience") || "") || undefined, representativeAchievements: String(formData.get("representativeAchievements") || "") || undefined }; const request = await api("/api/v2/talent-change-requests", { requestType: "CREATE", payload: { talent }, attachmentIds: attachmentId ? [attachmentId] : [] }); setSubmitted({ requestId: request.id, attachmentId }); setMessage(attachmentId ? "申请已提交。附件通过安全扫描后，可选择 AI 提取候选内容；AI 不会自动写入。" : "申请已提交，等待管理员审核。"); if (!attachmentId) setTimeout(() => { router.push("/resources/talents"); router.refresh(); }, 500); } catch (error) { setMessage(error instanceof Error ? error.message : "提交失败"); } finally { setPending(false); } }
  async function extract() { if (!submitted?.attachmentId) return; setPending(true); try { const result = await api(`/api/v2/talent-change-requests/${submitted.requestId}/ai-extract`, { attachmentId: submitted.attachmentId }); if (result.status === "FAILED") { setMessage("智能提取暂不可用，可继续使用已手工填写的内容，申请不会受阻。"); return; } setSubmitted({ ...submitted, extractionId: result.id, candidate: result.candidateJson as Candidate }); setMessage("AI 候选内容已生成，请逐项核对并明确确认；未确认不会进入申请数据。"); } catch (error) { setMessage(error instanceof Error ? error.message : "提取失败"); } finally { setPending(false); } }
  async function confirm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!submitted?.extractionId) return; const data = new FormData(event.currentTarget); setPending(true); try { await api(`/api/v2/talent-change-requests/${submitted.requestId}/ai-confirm`, { extractionId: submitted.extractionId, workEducationExperience: String(data.get("workEducationExperience") || "") || undefined, representativeAchievements: String(data.get("representativeAchievements") || "") || undefined }); setMessage("候选内容已由你确认并写入申请，等待管理员审核。"); router.push("/resources/talents"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "确认失败"); } finally { setPending(false); } }
  if (submitted) return <section className="space-y-4 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">申请已提交</h2>{submitted.attachmentId && !submitted.candidate && <button type="button" disabled={pending} onClick={extract} className="rounded-xl border border-blue-200 px-4 py-2 text-blue-700">AI 提取简历候选内容</button>}{submitted.candidate && <form onSubmit={confirm} className="space-y-4"><Text name="workEducationExperience" label="工作与教育经历候选" defaultValue={submitted.candidate.workEducationExperience}/><Text name="representativeAchievements" label="代表性成果候选" defaultValue={submitted.candidate.representativeAchievements}/><button disabled={pending} className="rounded-xl bg-blue-600 px-4 py-2 text-white">人工核对无误并确认写入</button></form>}<p role="status" className="text-sm text-slate-600">{message}</p><button type="button" onClick={() => router.push("/resources/talents")} className="text-sm text-blue-600">返回人才库</button></section>;
  return <form onSubmit={submit} className="space-y-4 rounded-2xl bg-white p-5 shadow-sm"><Field name="name" label="姓名"/><label className="block text-sm">人才范围<select name="scopeType" className="mt-1 w-full rounded-xl border p-3"><option value="DOMESTIC">境内</option><option value="OVERSEAS">海外</option></select></label><Field name="organizationName" label="工作单位"/><Field name="title" label="职务/职称"/><Field name="professionalDirection" label="专业方向"/><label className="block text-sm">原始推荐人（默认本人）<select name="originalRecommenderPersonId" className="mt-1 w-full rounded-xl border p-3"><option value="">使用当前提交人</option>{people.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label><Text name="workEducationExperience" label="工作与教育经历（可选）"/><Text name="representativeAchievements" label="代表性成果（可选）"/><label className="block text-sm">简历或证明材料（可选）<input name="resume" type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" className="mt-1 block w-full rounded-xl border p-3"/></label><p className="text-xs leading-5 text-slate-500">原始推荐人与当前联系人默认均为提交人；人才档案不采集人才本人电话、邮箱、微信、证件号或住址。AI 仅生成候选内容，必须人工确认。</p>{message&&<p role="status" className="text-sm text-red-600">{message}</p>}<button disabled={pending} className="w-full rounded-xl bg-blue-600 p-3 font-medium text-white disabled:opacity-50">{pending?"处理中…":"提交审核"}</button></form>;
}
function Field({name,label}:{name:string;label:string}){return <label className="block text-sm">{label}<input required name={name} className="mt-1 w-full rounded-xl border p-3"/></label>}
function Text({name,label,defaultValue}:{name:string;label:string;defaultValue?:string}){return <label className="block text-sm">{label}<textarea name={name} defaultValue={defaultValue} rows={4} className="mt-1 w-full rounded-xl border p-3"/></label>}
