import { requireBusinessPageSession } from "@/lib/auth/guards";
import { resolvePermissionActor } from "@/modules/permissions/actor-resolver";
import { AIConfigService, AuditQueryService, BackupService, HealthService, RestoreService, SettingsService, WorkCalendarService } from "@/modules/system";
import { SystemConsole } from "@/components/system/system-console";
import Link from "next/link";
import { backupComplianceStatusLabel, businessLabel, serviceStatusLabel, systemHealthStatusLabel } from "@/components/admin/business-labels";

export const dynamic = "force-dynamic";
export default async function SystemAdminPage() {
  const actor = await resolvePermissionActor(await requireBusinessPageSession());
  const settingsService = new SettingsService(); const calendarService = new WorkCalendarService(); const healthService = new HealthService();
  const health = await healthService.detail({ actor });
  const [overview, settings, calendar] = await Promise.all([healthService.overview({ actor }), settingsService.list({ actor }), calendarService.listOverrides({ actor, year: Number(new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Shanghai", year: "numeric" }).format(new Date())) })]);
  const canMutate = actor.capabilities.has("system.high_privilege_manage"); const canBackup = actor.capabilities.has("backup.manage"); const canRestore = actor.capabilities.has("backup.restore");
  const [backupCatalog, latestRestore, ai, audit] = await Promise.all([canBackup ? new BackupService().list({ actor }) : null, canRestore ? new RestoreService().latest({ actor }) : null, actor.capabilities.has("ai.metrics.view") ? new AIConfigService().list({ actor }) : null, actor.capabilities.has("audit.full_view") ? new AuditQueryService().list({ actor, query: { pageSize: 10 } }) : null]);
  return <section className="space-y-8"><header><p className="text-sm font-medium text-blue-700">系统管理</p><h1 className="mt-1 text-3xl font-semibold">系统治理</h1><p className="mt-2 text-slate-600">运行状态、配置、智能服务、地图、审计与备份恢复。业务时区固定为北京时间。</p></header><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">运行状态</h2><p className="mt-2 text-sm">总体：{businessLabel(systemHealthStatusLabel, overview.status)}</p><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-slate-500">失败任务</dt><dd className="font-semibold">{overview.alerts.failedJobs}</dd></div><div><dt className="text-slate-500">待投递事件</dt><dd className="font-semibold">{overview.alerts.unpublishedOutbox}</dd></div><div><dt className="text-slate-500">备份合规</dt><dd className="font-semibold">{businessLabel(backupComplianceStatusLabel, overview.alerts.backup)}</dd></div></dl>{health && <details className="mt-4"><summary className="min-h-11 cursor-pointer content-center text-sm text-blue-700">查看敏感健康详情（仅超级管理员）</summary><pre className="mt-3 max-h-96 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(health, (_, value) => typeof value === "bigint" ? value.toString() : value, 2)}</pre></details>}</section><SystemConsole settings={settings} calendar={calendar} backups={backupCatalog?.items ?? []} backupHealth={backupCatalog?.health ?? null} latestRestore={latestRestore} aiConfigs={ai?.configs ?? []} aiAllowlist={ai?.allowlist ?? []} canMutate={canMutate} canBackup={canBackup} canRestore={canRestore} canAIManage={actor.capabilities.has("ai.service.manage")}/>{ai && <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">智能服务安全运行信息</h2><p className="mt-1 text-sm text-slate-500">只显示服务能力、供应商、模型和运行状态；不显示私人正文、原始请求、手机号或票据正文。</p><div className="mt-4 divide-y text-sm">{ai.configs.map((item) => <p key={String(item.id)} className="py-3">{String(item.capability)} · {String(item.provider)}/{String(item.model)} · {businessLabel(serviceStatusLabel, String(item.status))} · 密钥{item.secretConfigured ? "已配置" : "未配置"}</p>)}</div></section>}{audit && <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">完整审计（脱敏）</h2><p className="mt-1 text-sm text-slate-500">最近 {audit.items.length} 条；审计不可在 UI 删除。</p></div><Link href="/admin/system/audit" className="min-h-11 content-center rounded-lg border px-3 py-2 text-sm text-blue-700">筛选全部审计</Link></div><div className="mt-4 divide-y text-sm">{audit.items.map((item) => <details key={item.id} className="py-3"><summary>{item.createdAt.toISOString()} · {item.actionCode} · {item.entityType}</summary><pre className="mt-2 overflow-auto rounded-lg bg-slate-100 p-3 text-xs">{JSON.stringify({ before: item.beforeJson, after: item.afterJson, reason: item.reason, requestId: item.requestId }, null, 2)}</pre></details>)}</div></section>}</section>;
}
