"use client";

import { useRouter } from "next/navigation";
import { type FormEvent, useState } from "react";

type Option = { id: string; name: string };
async function mutate(url: string, body: unknown) {
  const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json() as { ok: boolean; data?: { id?: string }; error?: { message?: string } };
  if (!response.ok || !data.ok) throw new Error(data.error?.message ?? "操作失败"); return data;
}
function useMutation() { const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); return { router, message, setMessage, busy, setBusy }; }

export function AdminEnterpriseCreateForm({ areas, tags }: { areas: Option[]; tags: Option[] }) {
  const state = useMutation();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); state.setBusy(true); state.setMessage(""); const data = new FormData(event.currentTarget);
    try { const result = await mutate("/api/v2/enterprises", { name: data.get("name"), responsibleAreaId: data.get("responsibleAreaId"), address: data.get("address"), creditCode: data.get("creditCode") || undefined, legalRepresentative: data.get("legalRepresentative") || undefined, introduction: data.get("introduction") || undefined, mainProducts: data.get("mainProducts"), qualificationsHonors: data.get("qualificationsHonors") || undefined, tagIds: data.getAll("tagIds") }); state.router.push(`/admin/enterprises/${result.data?.id}`); }
    catch (error) { state.setMessage(error instanceof Error ? error.message : "操作失败"); } finally { state.setBusy(false); }
  }
  return <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><Field name="name" label="企业名称" required/><label className="text-sm font-medium">所属区域<select name="responsibleAreaId" required className="mt-1 w-full rounded-xl border border-slate-200 p-3"><option value="">请选择</option>{areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><Field name="address" label="地址" required/><Field name="creditCode" label="统一社会信用代码"/><Field name="legalRepresentative" label="法定代表人"/><div/><TextArea name="mainProducts" label="主要产品/服务" required/><TextArea name="introduction" label="企业简介"/><TextArea name="qualificationsHonors" label="资质荣誉"/><fieldset><legend className="text-sm font-medium">标签</legend><div className="mt-2 flex flex-wrap gap-3">{tags.map((t) => <label key={t.id} className="text-sm"><input name="tagIds" value={t.id} type="checkbox" className="mr-1"/>{t.name}</label>)}</div></fieldset><div className="md:col-span-2"><button disabled={state.busy} className="rounded-xl bg-blue-600 px-5 py-3 font-medium text-white">{state.busy ? "保存中…" : "创建正式企业"}</button>{state.message && <p role="status" className="mt-2 text-sm text-red-600">{state.message}</p>}</div></form>;
}

export function EnterpriseGovernanceActions({ id, status, mergeTargets }: { id: string; status: string; mergeTargets: Option[] }) {
  const state = useMutation();
  async function simple(path: string, body: unknown) { state.setBusy(true); state.setMessage(""); try { await mutate(`/api/v2/enterprises/${id}/${path}`, body); state.setMessage("操作成功"); state.router.refresh(); } catch (e) { state.setMessage(e instanceof Error ? e.message : "操作失败"); } finally { state.setBusy(false); } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">治理操作</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">
    {status === "NORMAL" && <ReasonForm label="停用企业" danger onSubmit={(reason) => simple("disable", { reason })} />}{status === "DISABLED" && <ReasonForm label="恢复企业" onSubmit={(reason) => simple("restore", { reason })} />}
    {status !== "MERGED" && <form onSubmit={(e) => { e.preventDefault(); const d = new FormData(e.currentTarget); void simple("coordinate", { latitude: Number(d.get("latitude")), longitude: Number(d.get("longitude")) }); }} className="space-y-2 rounded-xl bg-slate-50 p-4"><p className="text-sm font-medium">人工坐标纠正</p><div className="grid grid-cols-2 gap-2"><input name="latitude" type="number" step="any" required placeholder="纬度" className="rounded-lg border p-2"/><input name="longitude" type="number" step="any" required placeholder="经度" className="rounded-lg border p-2"/></div><button className="rounded-lg border px-3 py-2 text-sm">保存坐标</button></form>}
    {status !== "MERGED" && <form onSubmit={(e) => { e.preventDefault(); const d = new FormData(e.currentTarget); if (!confirm("合并后源企业只读且不能恢复，确认继续？")) return; void simple("merge", { targetEnterpriseId: d.get("targetEnterpriseId"), reason: d.get("reason"), confirmation: "CONFIRM" }); }} className="space-y-2 rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-sm font-medium text-red-800">高风险：合并企业</p><select name="targetEnterpriseId" required className="w-full rounded-lg border p-2"><option value="">选择承接企业</option>{mergeTargets.filter((x) => x.id !== id).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="reason" required placeholder="合并原因" className="w-full rounded-lg border p-2"/><button className="rounded-lg bg-red-700 px-3 py-2 text-sm text-white">确认合并</button></form>}
  </div>{state.message && <p role="status" className="mt-3 text-sm text-blue-700">{state.message}</p>}</section>;
}

export function EnterpriseContactManager({ enterpriseId, contacts }: { enterpriseId: string; contacts: Array<{ id: string; name: string; phone: string; positionTitle: string | null; isPrimary: boolean; status: string }> }) {
  const state = useMutation(); async function act(url: string, body: unknown) { state.setBusy(true); try { await mutate(url, body); state.router.refresh(); state.setMessage("联系人已更新"); } catch(e) { state.setMessage(e instanceof Error ? e.message : "操作失败"); } finally { state.setBusy(false); } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">联系人</h2><div className="mt-3 divide-y">{contacts.map((c) => <div key={c.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><span>{c.name} · {c.positionTitle || "未填写职务"} · {c.phone} {c.isPrimary && <b className="text-blue-600">主要</b>} {c.status === "INACTIVE" && <span className="text-slate-400">已停用</span>}</span>{c.status === "ACTIVE" && <span className="space-x-2">{!c.isPrimary && <button onClick={() => act(`/api/v2/enterprise-contacts/${c.id}/set-primary`, {})} className="text-blue-600">设为主要</button>}<button onClick={() => { const replacementContactId = c.isPrimary ? prompt("请输入替代联系人的 ID") : undefined; if (c.isPrimary && !replacementContactId) return; void act(`/api/v2/enterprise-contacts/${c.id}/disable`, { reason: "管理端停用联系人", replacementContactId }); }} className="text-red-600">停用</button></span>}</div>)}</div>
    <form onSubmit={(e) => { e.preventDefault(); const d = new FormData(e.currentTarget); void act(`/api/v2/enterprises/${enterpriseId}/contacts`, { name: d.get("name"), positionTitle: d.get("positionTitle") || undefined, phone: d.get("phone"), setPrimary: d.get("setPrimary") === "on" }); }} className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-4 md:grid-cols-4"><input name="name" required placeholder="姓名" className="rounded-lg border p-2"/><input name="positionTitle" placeholder="职务" className="rounded-lg border p-2"/><input name="phone" required placeholder="手机或座机" className="rounded-lg border p-2"/><label className="flex items-center gap-2 text-sm"><input name="setPrimary" type="checkbox"/>设为主要</label><button disabled={state.busy} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white md:col-span-4">新增联系人</button></form>{state.message && <p className="mt-2 text-sm">{state.message}</p>}</section>;
}

export function ChangeRequestReview({ id, status }: { id: string; status: string }) { const state = useMutation(); async function review(decision: string) { const reason = decision === "APPROVE" ? prompt("审核说明（可选）") : prompt("请输入退回/关闭原因"); if (decision !== "APPROVE" && !reason) return; state.setBusy(true); try { await mutate(`/api/v2/enterprise-change-requests/${id}/review`, { decision, reason: reason || undefined }); state.router.refresh(); state.setMessage("审核已完成"); } catch(e) { state.setMessage(e instanceof Error ? e.message : "审核失败"); } finally { state.setBusy(false); } }
  if (status !== "PENDING_REVIEW") return <p className="text-sm text-slate-500">该申请已处理，不可重复审核。</p>;
  return <div><div className="flex gap-2"><button disabled={state.busy} onClick={() => review("APPROVE")} className="rounded-lg bg-emerald-600 px-4 py-2 text-white">通过</button><button disabled={state.busy} onClick={() => review("RETURN")} className="rounded-lg bg-amber-600 px-4 py-2 text-white">退回</button><button disabled={state.busy} onClick={() => review("CLOSE")} className="rounded-lg bg-slate-700 px-4 py-2 text-white">关闭</button></div>{state.message && <p className="mt-2 text-sm">{state.message}</p>}</div>;
}

function ReasonForm({ label, danger, onSubmit }: { label: string; danger?: boolean; onSubmit: (reason: string) => void }) { return <form onSubmit={(e) => { e.preventDefault(); onSubmit(String(new FormData(e.currentTarget).get("reason"))); }} className="space-y-2 rounded-xl bg-slate-50 p-4"><p className="text-sm font-medium">{label}</p><input name="reason" required placeholder="操作原因" className="w-full rounded-lg border p-2"/><button className={`rounded-lg px-3 py-2 text-sm text-white ${danger ? "bg-red-700" : "bg-blue-600"}`}>{label}</button></form>; }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="text-sm font-medium">{label}<input {...props} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>; }
function TextArea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) { return <label className="text-sm font-medium">{label}<textarea {...props} rows={4} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>; }
