import { notFound } from "next/navigation";
import { AttachmentOpenButton } from "@/components/policy/attachment-open-button";
import { policyPageContext } from "@/lib/policy/page-context";
import { PolicyError } from "@/modules/policy";

type Snapshot = { interpretation?: { targetAudience?: string; supportContent?: string; applicationConditions?: string; keyClauses?: string[]; evidence?: Array<{ field?: string; value?: string; page?: number; locator?: string }> } };

export default async function PolicyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { actor, service } = await policyPageContext(); let policy;
  try { policy = await service.detail({ actor, policyId: (await params).id }); } catch (error) { if (error instanceof PolicyError && error.status === 404) notFound(); throw error; }
  const current = policy.versions.find(({ id }) => id === policy.currentVersionId); const snap = current?.snapshotJson as Snapshot | undefined; const interpretation = snap?.interpretation;
  return <article className="space-y-5"><header><p className="text-sm text-blue-600">政策详情</p><h1 className="mt-1 text-2xl font-semibold">{policy.title}</h1><p className="mt-2 text-sm text-slate-600">{policy.issuingDepartment} · {policy.publicationDate.toISOString().slice(0, 10)} · {policy.level}</p><span className="mt-3 inline-block rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{policy.effectStatus === "CURRENT" ? "现行" : "已被替代"}</span></header><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">原政策文件</h2><div className="mt-3 space-y-2 text-sm">{current?.attachments.map((file) => <div key={file.id}><span className="mr-2 text-xs text-slate-500">{file.relationType === "PRIMARY" ? "主文件" : "补充附件"}</span><AttachmentOpenButton id={file.id} label={file.filename}/></div>)}</div></section><section className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><p className="text-xs font-medium text-blue-700">AI 智能解读，仅供内部辅助</p><h2 className="mt-1 font-semibold">智能解读</h2>{interpretation ? <dl className="mt-4 space-y-4 text-sm"><div><dt className="font-medium">适用对象</dt><dd className="mt-1 whitespace-pre-wrap text-slate-700">{interpretation.targetAudience}</dd></div><div><dt className="font-medium">支持内容</dt><dd className="mt-1 whitespace-pre-wrap text-slate-700">{interpretation.supportContent}</dd></div><div><dt className="font-medium">申报条件</dt><dd className="mt-1 whitespace-pre-wrap text-slate-700">{interpretation.applicationConditions}</dd></div><div><dt className="font-medium">关键条款</dt><dd><ul className="mt-1 list-disc space-y-1 pl-5 text-slate-700">{interpretation.keyClauses?.map((clause) => <li key={clause}>{clause}</li>)}</ul></dd></div><div><dt className="font-medium">原文依据</dt><dd className="mt-1 text-slate-700">{interpretation.evidence?.map((item, index) => <p key={index}>{item.field}：{item.value}{item.page ? `（第 ${item.page} 页）` : ""}{item.locator ? ` · ${item.locator}` : ""}</p>)}</dd></div></dl> : <p className="mt-3 text-sm text-slate-600">当前版本采用人工录入，尚无智能解读。</p>}</section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-semibold">替代关系</h2><div className="mt-2 space-y-1 text-sm text-slate-600">{policy.replacementsAsNew.map((relation) => <p key={relation.id}>替代：{relation.oldPolicy.title}{relation.endedAt ? "（关系已解除）" : ""}</p>)}{policy.replacementsAsOld.map((relation) => <p key={relation.id}>被替代于：{relation.newPolicy.title}{relation.endedAt ? "（关系已解除）" : ""}</p>)}{!policy.replacementsAsNew.length && !policy.replacementsAsOld.length && <p>无替代关系。</p>}</div></section></article>;
}
