import Link from "next/link";
import { MapCanvas } from "@/components/map/map-canvas";
import { NavigationLink } from "@/components/map/navigation-link";
import { enterprisePageContext } from "@/lib/enterprise/page-context";
import { mapPageContext } from "@/lib/map/page-context";
import { enterpriseListQuerySchema } from "@/modules/enterprise/schemas";
import { geoJsonCenter } from "@/modules/map/geojson";
import { enterpriseMapDetailQuerySchema } from "@/modules/map/schemas";
import type { MapPoint } from "@/modules/map/client/map-renderer";

export default async function EnterpriseListPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const view = params.view === "map" ? "map" : "list";
  const { actor, service } = await enterprisePageContext();
  const query = enterpriseListQuerySchema.parse({ keyword: typeof params.keyword === "string" ? params.keyword : undefined, areaId: typeof params.areaId === "string" ? params.areaId : undefined, tagId: typeof params.tagId === "string" ? params.tagId : undefined, page: typeof params.page === "string" ? params.page : undefined, pageSize: 20 });
  const options = await service.formOptions({ actor, purpose: "READ_FILTER" });
  const tabs = <nav className="mt-4 flex rounded-xl bg-slate-200/60 p-1"><Link href="/resources/enterprises" className={`flex-1 rounded-lg px-4 py-2 text-center text-sm ${view === "list" ? "bg-white font-medium shadow-sm" : "text-slate-500"}`}>列表</Link><Link href="/resources/enterprises?view=map" className={`flex-1 rounded-lg px-4 py-2 text-center text-sm ${view === "map" ? "bg-white font-medium shadow-sm" : "text-slate-500"}`}>地图</Link></nav>;
  if (view === "list") {
    const result = await service.list({ actor, query });
    return <section><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-blue-600">企业资源</p><h2 className="mt-1 text-2xl font-semibold">企业名录</h2></div>{actor.capabilities.has("enterprise.create_application") && <Link href="/resources/enterprises/apply" className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-medium text-white">新增申请</Link>}</div>{tabs}<form className="mt-5 grid gap-3 rounded-2xl bg-white p-4 shadow-sm"><input name="keyword" defaultValue={query.keyword} placeholder="搜索企业名称或主要产品" className="rounded-xl border border-slate-200 p-3"/><div className="grid grid-cols-[1fr_auto] gap-2"><select name="areaId" defaultValue={query.areaId} className="rounded-xl border border-slate-200 p-3"><option value="">全部区域</option>{options.areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="rounded-xl bg-slate-900 px-4 text-white">查询</button></div></form><p className="mt-4 text-sm text-slate-500">共 {result.total} 家正常企业</p><div className="mt-3 space-y-3">{result.items.length === 0 ? <div className="rounded-2xl bg-white p-8 text-center text-slate-500">暂无符合条件的企业，请调整筛选条件。</div> : result.items.map((item) => <Link href={`/resources/enterprises/${item.id}`} key={item.id} className="block rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><h3 className="font-semibold">{item.name}</h3><span className="text-xs text-slate-500">{item.responsibleArea.name}</span></div><p className="mt-2 text-sm text-slate-600">{item.mainProducts}</p></Link>)}</div></section>;
  }
  const { maps } = await mapPageContext(); const summary = await maps.enterpriseAreas({ actor }); const selectedAreaId = typeof params.areaId === "string" ? params.areaId : null;
  const mapQuery = enterpriseMapDetailQuerySchema.parse({ page: typeof params.page === "string" ? params.page : undefined, pageSize: 100 });
  const detail = selectedAreaId ? await maps.enterpriseAreaDetail({ actor, areaId: selectedAreaId, ...mapQuery }) : null;
  const versions = detail?.boundary ? [detail.boundary] : [summary.countyBoundary, ...summary.areas.map((area) => area.currentBoundaryVersion)].filter((item): item is NonNullable<typeof item> => !!item);
  const boundaries = versions.map((item) => ({ id: item.id, geoJson: item.geoJson }));
  const points: MapPoint[] = detail ? detail.enterprises.filter((item) => item.hasValidCoordinate).map((item) => ({ id: item.id, name: item.name, latitude: Number(item.latitude), longitude: Number(item.longitude), color: "blue" })) : summary.areas.flatMap((area) => { const center = area.currentBoundaryVersion ? geoJsonCenter(area.currentBoundaryVersion.geoJson) : null; return center ? [{ id: area.id, name: area.name, ...center, label: String(area.count), color: "blue" as const }] : []; });
  if (summary.runtime.countyGovernmentLandmark) points.push({ id: "county-government", name: summary.runtime.countyGovernmentLandmark.name, latitude: summary.runtime.countyGovernmentLandmark.latitude, longitude: summary.runtime.countyGovernmentLandmark.longitude, label: "★", color: "red" });
  const boundaryCenter = detail?.boundary ? geoJsonCenter(detail.boundary.geoJson) : summary.countyBoundary ? geoJsonCenter(summary.countyBoundary.geoJson) : summary.areas.map((area) => area.currentBoundaryVersion ? geoJsonCenter(area.currentBoundaryVersion.geoJson) : null).find((item) => item !== null) ?? null;
  const totalPages = detail ? Math.max(1, Math.ceil(detail.total / detail.pageSize)) : 1;
  const areaPageHref = (page: number) => `/resources/enterprises?view=map&areaId=${encodeURIComponent(selectedAreaId ?? "")}&page=${page}`;
  return <section><p className="text-sm text-blue-600">企业资源</p><h1 className="mt-1 text-2xl font-semibold">企业地图</h1>{tabs}<div className="mt-4"><MapCanvas mapKey={summary.runtime.tencentMapKey} center={boundaryCenter} boundaries={boundaries} points={points} emptyMessage="尚未导入并激活边界，企业列表仍可使用。" /></div>{detail ? <div className="mt-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{detail.area.name}</h2><p className="text-sm text-slate-500">{detail.total} 家正式企业 · 地图显示当前页企业</p></div><Link href="/resources/enterprises?view=map" className="text-sm font-medium text-blue-600">查看全县</Link></div><div className="mt-3 space-y-3">{detail.enterprises.map((item) => <article key={item.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><strong>{item.name}</strong><span className="text-xs text-slate-500">{item.hasValidCoordinate ? "已定位" : "定位待完善"}</span></div><p className="mt-2 text-sm text-slate-600">{item.mainProducts}</p><p className="mt-2 text-xs text-slate-500">{item.primaryContact ? `${item.primaryContact.name} · ${item.primaryContact.phone}` : "暂无主要联系人"}</p><div className="mt-3 flex gap-4"><Link href={`/resources/enterprises/${item.id}`} className="text-sm font-medium text-blue-600">详情</Link>{item.primaryContact && <a href={`tel:${item.primaryContact.phone}`} className="text-sm font-medium text-blue-600">拨号</a>}<NavigationLink name={item.name} address={item.address} latitude={item.latitude ? Number(item.latitude) : null} longitude={item.longitude ? Number(item.longitude) : null}/></div></article>)}</div><nav aria-label="企业地图分页" className="mt-4 flex items-center justify-between rounded-xl bg-white p-3 text-sm"><span>第 {detail.page} / {totalPages} 页 · 共 {detail.total} 家</span><span className="flex gap-3">{detail.page > 1 ? <Link className="font-medium text-blue-600" href={areaPageHref(detail.page - 1)}>上一页</Link> : <span className="text-slate-300">上一页</span>}{detail.page < totalPages ? <Link className="font-medium text-blue-600" href={areaPageHref(detail.page + 1)}>下一页</Link> : <span className="text-slate-300">下一页</span>}</span></nav></div> : <div className="mt-4 grid grid-cols-2 gap-3">{summary.areas.map((area) => <Link key={area.id} href={`/resources/enterprises?view=map&areaId=${area.id}`} className="rounded-2xl bg-white p-4 shadow-sm"><strong className="block text-sm">{area.name}</strong><span className="mt-2 block text-2xl font-semibold text-blue-600">{area.count}</span><span className="text-xs text-slate-500">正式归属企业</span></Link>)}</div>}</section>;
}
