import { describe,expect,it,vi } from "vitest"; import type { RoleCode } from "@/generated/prisma/client"; import { isHelpCommandIdempotencyUniqueConflict } from "@/modules/help/errors"; import { HelpService,isHelpOverdue,requireFutureExpectedDate } from "@/modules/help/help-service"; import { HelpRepository } from "@/modules/help/repository/help-repository"; import { addHelpProgressSchema,assignHelpPersonSchema,completeHelpRequestSchema,createHelpRequestSchema,helpListQuerySchema,helpReasonSchema,reassignHelpRequestSchema } from "@/modules/help/schemas"; import { authorizeActor,resolveCapabilities,type PermissionActor } from "@/modules/permissions";
function actor(roles:RoleCode[],overrides:Partial<PermissionActor>={}):PermissionActor{const capabilities=resolveCapabilities(roles,new Set());return{personId:"person",accountId:"account",accountStatus:"NORMAL",permissionVersion:BigInt(1),effectiveRoles:roles,capabilities,specialPermissions:new Set(),selfPersonId:"person",townshipAreaIds:[],departmentAreaIds:[],hasGlobalPublished:true,hasGlobalOperational:roles.includes("ADMIN")||roles.includes("SUPER_ADMIN"),hasSystem:roles.includes("SUPER_ADMIN"),currentBatchMember:roles.includes("MEMBER_CURRENT"),configurationIssues:[],...overrides};}
const base={category:"ACCOMMODATION",title:"安排住宿",description:"来宝期间需要住宿",urgency:"NORMAL",attachmentIds:[]};
describe("C-M3-002 help input and derived state",()=>{
 it("accepts all documented categories including dining",()=>{for(const category of ["ACCOMMODATION","TRANSPORTATION","DINING","WORK","LIFE","OTHER"])expect(createHelpRequestSchema.safeParse({...base,category}).success).toBe(true);});
 it("rejects lifecycle and owner mass assignment",()=>{expect(createHelpRequestSchema.safeParse({...base,status:"COMPLETED",currentOwnerPersonId:crypto.randomUUID()}).success).toBe(false);});
 it("strictly validates transition command shapes",()=>{expect(assignHelpPersonSchema.safeParse({personId:crypto.randomUUID(),expectedCompleteAt:new Date(Date.now()+60_000)}).success).toBe(true);expect(addHelpProgressSchema.safeParse({content:"",attachmentIds:[]}).success).toBe(false);expect(completeHelpRequestSchema.safeParse({completionSummary:""}).success).toBe(false);expect(helpReasonSchema.safeParse({reason:""}).success).toBe(false);expect(reassignHelpRequestSchema.safeParse({targetType:"ORGANIZATION",personId:crypto.randomUUID(),reason:"改派"}).success).toBe(false);});
 it("derives overdue only for in-progress work",()=>{const expectedCompleteAt=new Date("2026-01-01");const now=new Date("2026-01-02");expect(isHelpOverdue({status:"IN_PROGRESS",expectedCompleteAt},now)).toBe(true);for(const status of ["PENDING","COMPLETED","WITHDRAWN"] as const)expect(isHelpOverdue({status,expectedCompleteAt},now)).toBe(false);});
 it("requires a valid future expected date",()=>{expect(()=>requireFutureExpectedDate(new Date("2026-01-02"),new Date("2026-01-01"))).not.toThrow();expect(()=>requireFutureExpectedDate(new Date("2025-12-31"),new Date("2026-01-01"))).toThrowError(expect.objectContaining({code:"HELP_EXPECTED_DATE_INVALID"}));});
 it("normalizes private list modes and filters",()=>{expect(helpListQuerySchema.parse({mode:"handled",overdue:"true",page:"2"})).toMatchObject({mode:"handled",overdue:true,page:2,pageSize:20});});
 it("recognizes only the Help claim idempotency unique constraint",()=>{expect(isHelpCommandIdempotencyUniqueConflict({code:"P2002",meta:{constraint:"help_claim_idempotency_key"}})).toBe(true);expect(isHelpCommandIdempotencyUniqueConflict({code:"P2002",meta:{target:["actor_person_id","action_code","idempotency_key_hash"]}})).toBe(true);expect(isHelpCommandIdempotencyUniqueConflict({code:"P2002",meta:{target:["business_no"]}})).toBe(false);expect(isHelpCommandIdempotencyUniqueConflict(new Error("not a Prisma conflict"))).toBe(false);});
});
describe("C-M3-002 help permission and relation boundaries",()=>{
 it("allows create only for a current member and denies alumni",async()=>{await expect(authorizeActor({actor:actor(["MEMBER_CURRENT"]),action:"help.create"})).resolves.toMatchObject({allowed:true});await expect(authorizeActor({actor:actor(["MEMBER_ALUMNI_PLATFORM"]),action:"help.create"})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});});
 it("keeps self withdraw and reopen capabilities after the submitter becomes alumni",()=>{const alumni=actor(["MEMBER_ALUMNI_PLATFORM"]);expect(alumni.capabilities.has("help.create")).toBe(false);expect(alumni.capabilities.has("help.withdraw")).toBe(true);expect(alumni.capabilities.has("help.reopen")).toBe(true);});
 it("does not grant minister or group leader global private visibility",()=>{for(const role of ["MINISTER","GROUP_LEADER"] as const){const value=actor([role]);expect(value.capabilities.has("help.view")).toBe(true);expect(value.hasGlobalOperational).toBe(false);expect(value.capabilities.has("help.assign")).toBe(false);}});
 it("resolves current organization membership from active Appointment records",async()=>{const findMany=vi.fn().mockResolvedValue([{organizationId:"org-a"},{organizationId:"org-a"}]);const repository=new HelpRepository({appointment:{findMany}} as never);await expect(repository.currentOrganizationIds({appointment:{findMany}} as never,"person",new Date("2026-01-01"))).resolves.toEqual(["org-a"]);expect(findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({personId:"person",organization:expect.objectContaining({status:"ACTIVE"})})}));});
 it("enforces private visibility and owner gates before returning detail or completing",async()=>{const unrelated={transaction:async(operation:(tx:object)=>Promise<unknown>)=>operation({}) ,findVisible:vi.fn().mockResolvedValue(null)} as unknown as HelpRepository;await expect(new HelpService(unrelated).detail({actor:actor(["MINISTER"]),helpRequestId:crypto.randomUUID()})).rejects.toMatchObject({code:"HELP_NOT_FOUND"});const denied=actor(["MEMBER_CURRENT"],{personId:"not-owner"});const help={id:crypto.randomUUID(),status:"IN_PROGRESS",currentOwnerPersonId:"owner"};const tx={};const repository={transaction:async(operation:(value:typeof tx)=>Promise<unknown>)=>operation(tx),lockHelp:vi.fn(),findById:vi.fn().mockResolvedValue(help)} as unknown as HelpRepository;await expect(new HelpService(repository).complete({actor:denied,helpRequestId:help.id,body:{completionSummary:"完成"}})).rejects.toMatchObject({code:"HELP_FORBIDDEN"});});
});
