import { describe,expect,it } from "vitest"; import type { RoleCode } from "@/generated/prisma/client"; import { authorizeActor,resolveCapabilities,type PermissionActor } from "@/modules/permissions"; import { addTalentProgressSchema,changeContactPersonSchema,confirmAIExtractionSchema,createTalentChangeRequestSchema,mergeTalentSchema,talentCoreSchema,talentListQuerySchema } from "@/modules/talent/schemas";
function actor(roles:RoleCode[],townshipAreaIds:string[]=[]):PermissionActor{const capabilities=resolveCapabilities(roles,new Set());return{personId:"p",accountId:"a",accountStatus:"NORMAL",permissionVersion:BigInt(1),effectiveRoles:roles,capabilities,specialPermissions:new Set(),selfPersonId:"p",townshipAreaIds,departmentAreaIds:[],hasGlobalPublished:true,hasGlobalOperational:roles.includes("ADMIN")||roles.includes("SUPER_ADMIN"),hasSystem:roles.includes("SUPER_ADMIN"),currentBatchMember:roles.includes("MEMBER_CURRENT"),configurationIssues:[]};}
const core={name:"张人才",scopeType:"DOMESTIC",organizationName:"清华大学",title:"教授",professionalDirection:"人工智能"};
describe("C-M2-005 talent boundaries",()=>{
 it("accepts the talent core without external contact fields",()=>{expect(talentCoreSchema.parse(core)).toEqual(core);for(const forbidden of ["phone","mobile","email","wechat","idNumber","address"])expect(talentCoreSchema.safeParse({...core,[forbidden]:"secret"}).success).toBe(false);});
 it("rejects formal state mass assignment",()=>{expect(talentCoreSchema.safeParse({...core,status:"MERGED",currentContactPersonId:crypto.randomUUID()}).success).toBe(false);});
 it("requires explicit merge confirmation and reason",()=>{expect(mergeTalentSchema.safeParse({targetTalentId:crypto.randomUUID(),reason:"重复",confirmation:"yes"}).success).toBe(false);expect(mergeTalentSchema.safeParse({targetTalentId:crypto.randomUUID(),reason:"重复",confirmation:"CONFIRM"}).success).toBe(true);});
 it("normalizes list paging and caps page size",()=>{expect(talentListQuerySchema.parse({keyword:" 人工智能 ",page:"2",pageSize:"100"})).toMatchObject({keyword:"人工智能",page:2,pageSize:100});expect(talentListQuerySchema.safeParse({pageSize:101}).success).toBe(false);});
 it("requires a reason to change current contact",()=>{expect(changeContactPersonSchema.safeParse({personId:crypto.randomUUID(),reason:""}).success).toBe(false);});
 it("allows only whitelisted AI confirmation fields",()=>{expect(confirmAIExtractionSchema.safeParse({extractionId:crypto.randomUUID(),workEducationExperience:"经历",phone:"13800000000"}).success).toBe(false);});
 it("bounds append-only progress",()=>{expect(addTalentProgressSchema.safeParse({content:"进展",nextStep:"下一步"}).success).toBe(true);expect(addTalentProgressSchema.safeParse({content:"x".repeat(2001)}).success).toBe(false);});
 it("validates create and correction request shapes",()=>{expect(createTalentChangeRequestSchema.safeParse({requestType:"CREATE",payload:{talent:core}}).success).toBe(true);expect(createTalentChangeRequestSchema.safeParse({requestType:"CORRECTION",targetTalentId:crypto.randomUUID(),baseTalentVersion:1,payload:{changes:{status:"DISABLED"}}}).success).toBe(false);});
});
describe("C-M2-005 talent permission matrix",()=>{
 it("keeps governance administrative and submission broad",async()=>{const member=actor(["MEMBER_CURRENT"]),admin=actor(["ADMIN"]);await expect(authorizeActor({actor:member,action:"talent.submit"})).resolves.toMatchObject({allowed:true});await expect(authorizeActor({actor:member,action:"talent.merge"})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});for(const action of ["talent.review","talent.edit_formal","talent.contact_person.change","talent.merge","talent.disable","talent.round.void"] as const)expect(admin.capabilities.has(action)).toBe(true);});
 it("scopes round start and withdrawal to the township",async()=>{const township=actor(["TOWNSHIP_STAFF"],["area-a"]);await expect(authorizeActor({actor:township,action:"talent.contact.start",resource:{resourceType:"round",requiredScope:"TOWNSHIP",areaId:"area-a"}})).resolves.toMatchObject({allowed:true});await expect(authorizeActor({actor:township,action:"talent.contact.withdraw",resource:{resourceType:"round",requiredScope:"TOWNSHIP",areaId:"area-b"}})).rejects.toMatchObject({code:"FORBIDDEN_SCOPE"});});
 it("allows internal current-contact actions only after relation checks",()=>{const member=actor(["MEMBER_CURRENT"]);expect(member.capabilities.has("talent.contact.update")).toBe(true);expect(member.capabilities.has("talent.contact.complete")).toBe(true);expect(member.capabilities.has("talent.contact.start")).toBe(false);});
});
