import { describe,expect,it,vi } from "vitest"; import type { RoleCode } from "@/generated/prisma/client"; import { authorizeActor,resolveCapabilities,type PermissionActor } from "@/modules/permissions"; import { TalentService } from "@/modules/talent"; import { parseTalentExtractionOutput } from "@/modules/talent/extraction"; import { TalentRepository } from "@/modules/talent/repository/talent-repository"; import { addTalentProgressSchema,changeContactPersonSchema,confirmAIExtractionSchema,createTalentChangeRequestSchema,mergeTalentSchema,talentCoreSchema,talentListQuerySchema } from "@/modules/talent/schemas";
function actor(roles:RoleCode[],townshipAreaIds:string[]=[]):PermissionActor{const capabilities=resolveCapabilities(roles,new Set());return{personId:"p",accountId:"a",accountStatus:"NORMAL",permissionVersion:BigInt(1),effectiveRoles:roles,capabilities,specialPermissions:new Set(),selfPersonId:"p",townshipAreaIds,departmentAreaIds:[],hasGlobalPublished:true,hasGlobalOperational:roles.includes("ADMIN")||roles.includes("SUPER_ADMIN"),hasSystem:roles.includes("SUPER_ADMIN"),currentBatchMember:roles.includes("MEMBER_CURRENT"),configurationIssues:[]};}
const core={name:"张人才",scopeType:"DOMESTIC",organizationName:"清华大学",title:"教授",professionalDirection:"人工智能"};
describe("C-M2-005 talent boundaries",()=>{
 it("accepts the talent core without external contact fields",()=>{expect(talentCoreSchema.parse(core)).toEqual(core);for(const forbidden of ["phone","mobile","email","wechat","idNumber","address"])expect(talentCoreSchema.safeParse({...core,[forbidden]:"secret"}).success).toBe(false);});
 it("rejects formal state mass assignment",()=>{expect(talentCoreSchema.safeParse({...core,status:"MERGED",currentContactPersonId:crypto.randomUUID()}).success).toBe(false);});
 it("requires explicit merge confirmation and reason",()=>{expect(mergeTalentSchema.safeParse({targetTalentId:crypto.randomUUID(),reason:"重复",confirmation:"yes"}).success).toBe(false);expect(mergeTalentSchema.safeParse({targetTalentId:crypto.randomUUID(),reason:"重复",confirmation:"CONFIRM"}).success).toBe(true);});
 it("normalizes list paging and caps page size",()=>{expect(talentListQuerySchema.parse({keyword:" 人工智能 ",page:"2",pageSize:"100"})).toMatchObject({keyword:"人工智能",page:2,pageSize:100});expect(talentListQuerySchema.safeParse({pageSize:101}).success).toBe(false);});
 it("requires a reason to change current contact",()=>{expect(changeContactPersonSchema.safeParse({personId:crypto.randomUUID(),reason:""}).success).toBe(false);});
 it("allows only whitelisted AI confirmation fields",()=>{expect(confirmAIExtractionSchema.safeParse({extractionId:crypto.randomUUID(),workEducationExperience:"经历",phone:"13800000000"}).success).toBe(false);});
 it("bounds append-only progress",()=>{expect(addTalentProgressSchema.safeParse({content:"进展",nextStep:"下一步"}).success).toBe(true);expect(addTalentProgressSchema.safeParse({content:"x".repeat(2001)}).success).toBe(false);});
 it("validates create and correction request shapes",()=>{expect(createTalentChangeRequestSchema.safeParse({requestType:"CREATE",payload:{talent:core}}).success).toBe(true);expect(createTalentChangeRequestSchema.safeParse({requestType:"CORRECTION",targetTalentId:crypto.randomUUID(),baseTalentVersion:1,payload:{changes:{status:"DISABLED"}}}).success).toBe(false);});
});
describe("C-M2-005 talent permission matrix",()=>{
 it("keeps governance administrative and submission broad",async()=>{const member=actor(["MEMBER_CURRENT"]),admin=actor(["ADMIN"]);await expect(authorizeActor({actor:member,action:"talent.submit"})).resolves.toMatchObject({allowed:true});await expect(authorizeActor({actor:member,action:"talent.merge"})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});for(const action of ["talent.review","talent.edit_formal","talent.contact_person.change","talent.merge","talent.disable","talent.round.void"] as const)expect(admin.capabilities.has(action)).toBe(true);});
 it("scopes round start and withdrawal to the township",async()=>{const township=actor(["TOWNSHIP_STAFF"],["area-a"]);await expect(authorizeActor({actor:township,action:"talent.contact.start",resource:{resourceType:"round",requiredScope:"TOWNSHIP",areaId:"area-a"}})).resolves.toMatchObject({allowed:true});await expect(authorizeActor({actor:township,action:"talent.contact.withdraw",resource:{resourceType:"round",requiredScope:"TOWNSHIP",areaId:"area-b"}})).rejects.toMatchObject({code:"FORBIDDEN_SCOPE"});});
 it("allows internal current-contact actions only after relation checks",()=>{const member=actor(["MEMBER_CURRENT"]);expect(member.capabilities.has("talent.contact.update")).toBe(true);expect(member.capabilities.has("talent.contact.complete")).toBe(true);expect(member.capabilities.has("talent.contact.start")).toBe(false);});
});
describe("PR #15 talent hardening",()=>{
 it("runtime-validates the exact AI candidate whitelist and minimal evidence",()=>{const attachmentId=crypto.randomUUID();expect(parseTalentExtractionOutput({candidate:{workEducationExperience:"经历",structured:{experiences:[{organization:"研究院"}],projects:[],patents:[],papers:[],awards:[]}},evidence:{attachmentId,page:2,locator:"paragraph:3"}},attachmentId)).toMatchObject({candidate:{workEducationExperience:"经历"},evidence:{attachmentId,page:2,locator:"paragraph:3"}});expect(()=>parseTalentExtractionOutput({candidate:{workEducationExperience:"经历",unexpected:"禁止"},evidence:{attachmentId}},attachmentId)).toThrow("TALENT_AI_OUTPUT_UNSAFE");expect(()=>parseTalentExtractionOutput({candidate:{structured:{experiences:[{profile:{eMail:"private@example.com"}}]}},evidence:{attachmentId}},attachmentId)).toThrow("TALENT_AI_OUTPUT_UNSAFE");expect(()=>parseTalentExtractionOutput({candidate:{structured:{projects:[{微信:"secret"}]}},evidence:{attachmentId}},attachmentId)).toThrow("TALENT_AI_OUTPUT_UNSAFE");});
 it("rejects non-minimal or mismatched AI evidence",()=>{const attachmentId=crypto.randomUUID();expect(()=>parseTalentExtractionOutput({candidate:{},evidence:{attachmentId,rawText:"完整 OCR 正文"}},attachmentId)).toThrow("TALENT_AI_OUTPUT_UNSAFE");expect(()=>parseTalentExtractionOutput({candidate:{},evidence:{attachmentId:crypto.randomUUID()}},attachmentId)).toThrow("TALENT_AI_OUTPUT_UNSAFE");});
 it("rechecks submit permission before resubmit, extract, and confirm",async()=>{const denied=actor([]);const transaction=vi.fn();const service=new TalentService({transaction} as unknown as TalentRepository);await expect(service.resubmitChangeRequest({actor:denied,requestId:crypto.randomUUID(),body:{payload:{talent:core}}})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});await expect(service.extractAI({actor:denied,requestId:crypto.randomUUID(),attachmentId:crypto.randomUUID()})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});await expect(service.confirmAI({actor:denied,requestId:crypto.randomUUID(),extractionId:crypto.randomUUID()})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});expect(transaction).not.toHaveBeenCalled();});
 it("also rechecks correction permission for correction resubmit and AI actions",async()=>{const submitOnly={...actor([]),capabilities:new Set(["talent.submit" as const])};const requestId=crypto.randomUUID();const tx={talentChangeRequest:{findUnique:vi.fn().mockResolvedValue({id:requestId,requestType:"CORRECTION",status:"RETURNED",submitterPersonId:submitOnly.personId})}};const repository={transaction:async(operation:(value:typeof tx)=>Promise<unknown>)=>operation(tx),lockRequest:vi.fn().mockResolvedValue(undefined)} as unknown as TalentRepository;const service=new TalentService(repository);await expect(service.resubmitChangeRequest({actor:submitOnly,requestId,body:{payload:{changes:{title:"纠错"}},baseTalentVersion:1}})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});await expect(service.extractAI({actor:submitOnly,requestId,attachmentId:crypto.randomUUID()})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});await expect(service.confirmAI({actor:submitOnly,requestId,extractionId:crypto.randomUUID()})).rejects.toMatchObject({code:"FORBIDDEN_CAPABILITY"});});
 it("rejects confirm on APPROVED and extract on CLOSED requests",async()=>{const member=actor(["MEMBER_CURRENT"]);const approvedId=crypto.randomUUID();const approvedTx={talentChangeRequest:{findUnique:vi.fn().mockResolvedValue({id:approvedId,requestType:"CREATE",status:"APPROVED",submitterPersonId:member.personId})}};const approvedRepository={transaction:async(operation:(tx:typeof approvedTx)=>Promise<unknown>)=>operation(approvedTx),lockRequest:vi.fn().mockResolvedValue(undefined)} as unknown as TalentRepository;await expect(new TalentService(approvedRepository).confirmAI({actor:member,requestId:approvedId,extractionId:crypto.randomUUID()})).rejects.toMatchObject({code:"TALENT_REQUEST_STATE_CONFLICT",status:409});const closedId=crypto.randomUUID();const closedTx={talentChangeRequest:{findUnique:vi.fn().mockResolvedValue({id:closedId,requestType:"CREATE",status:"CLOSED",submitterPersonId:member.personId})}};const closedRepository={transaction:async(operation:(tx:typeof closedTx)=>Promise<unknown>)=>operation(closedTx),lockRequest:vi.fn().mockResolvedValue(undefined)} as unknown as TalentRepository;await expect(new TalentService(closedRepository).extractAI({actor:member,requestId:closedId,attachmentId:crypto.randomUUID()})).rejects.toMatchObject({code:"TALENT_REQUEST_STATE_CONFLICT",status:409});});
 it("keeps reviewer governance for an admin who submitted the request",async()=>{const admin=actor(["ADMIN"]);const request={id:crypto.randomUUID(),requestType:"CREATE",status:"PENDING_REVIEW",submitterPersonId:admin.personId,payloadSnapshot:{talent:core},submitterPerson:{id:admin.personId,name:"Admin"},reviewerPerson:null,targetTalent:null,approvedTalent:null,aiExtractions:[]};const duplicateCandidates=vi.fn().mockResolvedValue([{id:"duplicate"}]);const tx={};const repository={transaction:async(operation:(value:typeof tx)=>Promise<unknown>)=>operation(tx),findRequest:vi.fn().mockResolvedValue(request),duplicateCandidates} as unknown as TalentRepository;const result=await new TalentService(repository).getChangeRequest({actor:admin,requestId:request.id});expect(result.duplicateCandidates).toEqual([{id:"duplicate"}]);expect(duplicateCandidates).toHaveBeenCalledOnce();});
 it("filters disabled accounts from new-selection options",async()=>{const findMany=vi.fn().mockResolvedValue([]);const repository=new TalentRepository({person:{findMany}} as never);await repository.listInternalPeople();expect(findMany).toHaveBeenCalledWith(expect.objectContaining({where:{personStatus:"ACTIVE",account:{is:{status:{not:"DISABLED"}}}}}));});
});
