import Link from "next/link";
import { MapCanvas } from "@/components/map/map-canvas";
import { mapPageContext } from "@/lib/map/page-context";
import { memberFoundationPageContext } from "@/lib/member-foundation/page-context";

export default async function MembersPage({ searchParams }: { searchParams: Promise<{ kind?: string; keyword?: string; view?: string; dispatchOrganizationId?: string }> }) {
  const params = await searchParams;
  const kind = params.kind === "alumni" ? "alumni" : "current";
  const view = params.view === "map" ? "map" : "list";
  const { actor, members } = await memberFoundationPageContext();
  const tabs = <><nav className="mt-4 flex gap-2"><Link href={`/resources/members?kind=current&view=${view}`} className={`rounded-full px-4 py-2 text-sm ${kind === "current" ? "bg-blue-600 text-white" : "bg-white"}`}>在任</Link><Link href={`/resources/members?kind=alumni&view=${view}`} className={`rounded-full px-4 py-2 text-sm ${kind === "alumni" ? "bg-blue-600 text-white" : "bg-white"}`}>往届</Link></nav><nav className="mt-3 flex rounded-xl bg-slate-200/60 p-1"><Link href={`/resources/members?kind=${kind}`} className={`flex-1 rounded-lg px-4 py-2 text-center text-sm ${view === "list" ? "bg-white shadow-sm" : "text-slate-500"}`}>列表</Link><Link href={`/resources/members?kind=${kind}&view=map`} className={`flex-1 rounded-lg px-4 py-2 text-center text-sm ${view === "map" ? "bg-white shadow-sm" : "text-slate-500"}`}>地图</Link></nav></>;
  if (view === "list") {
    const result = await members.list({ actor, query: { kind, keyword: params.keyword?.trim() || undefined, page: 1, pageSize: 100 } });
    return <section><h1 className="text-2xl font-semibold">团员</h1><p className="mt-2 text-sm text-slate-500">Person 永久保留，多批次履历不会复制人员。</p>{tabs}<form className="mt-4 flex gap-2"><input type="hidden" name="kind" defaultValue={kind}/><input name="keyword" defaultValue={params.keyword} placeholder="搜索姓名" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white p-3"/><button className="rounded-xl bg-slate-900 px-4 text-sm text-white">搜索</button></form><div className="mt-4 space-y-3">{result.items.length ? result.items.map((member) => <Link key={member.id} href={`/resources/members/${member.id}`} className="block rounded-2xl bg-white p-4 shadow-sm"><strong>{member.name}</strong><p className="mt-1 text-sm text-slate-500">{member.memberships[0]?.dispatchOrganization?.name ?? "暂无派出单位"}</p><div className="mt-2 flex gap-2">{member.roles.filter(({ code }) => code === "GROUP_LEADER" || code === "MINISTER").map((role) => <span key={role.code} className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{role.label}</span>)}</div></Link>) : <p className="rounded-2xl bg-white p-6 text-center text-sm text-slate-500">暂无团员</p>}</div></section>;
  }
  const { maps } = await mapPageContext();
  const result = await maps.memberMap({ actor, query: { kind, keyword: params.keyword, dispatchOrganizationId: params.dispatchOrganizationId } });
  const points = result.points.filter((item) => item.organization.hasValidCoordinate).map((item) => ({ id: item.organization.id, name: item.organization.name, latitude: Number(item.organization.latitude), longitude: Number(item.organization.longitude), label: String(item.count), color: "blue" as const }));
  return <section><h1 className="text-2xl font-semibold">团员地图</h1><p className="mt-2 text-sm text-slate-500">展示派出单位地域分布，不是团员实时位置。</p>{tabs}<form className="mt-4 grid gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><input type="hidden" name="kind" defaultValue={kind}/><input type="hidden" name="view" defaultValue="map"/><select aria-label="派出单位" name="dispatchOrganizationId" defaultValue={params.dispatchOrganizationId ?? ""} className="rounded-xl border border-slate-200 bg-white p-3"><option value="">全部派出单位</option>{result.dispatchOrganizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><input name="keyword" defaultValue={params.keyword} placeholder="姓名、派出单位、专业方向" className="min-w-0 rounded-xl border border-slate-200 bg-white p-3"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-sm text-white">搜索</button></form><div className="mt-4"><MapCanvas mapKey={result.runtime.tencentMapKey} boundaries={[]} points={points} emptyMessage="暂无具备有效派出单位坐标的团员。"/></div>{result.unlocatedCount > 0 && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{result.unlocatedCount} 名团员或派出单位定位待完善；人员仍保留在列表。</p>}<div className="mt-4 space-y-3">{result.points.map((group) => <article key={group.organization.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between"><strong>{group.organization.name}</strong><span className="text-sm text-blue-600">{group.count} 人</span></div><p className="mt-1 text-xs text-slate-500">{group.organization.hasValidCoordinate ? "派出单位坐标已配置" : "定位待完善"}</p><div className="mt-3 flex flex-wrap gap-2">{group.members.map((member) => <Link key={member.id} href={`/resources/members/${member.id}`} className="rounded-full bg-slate-100 px-3 py-1 text-sm">{member.name}{member.professionalDirection ? ` · ${member.professionalDirection}` : ""}</Link>)}</div></article>)}</div></section>;
}
